// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: sys.proto

package server

import (
	"context"

	"zero-admin/rpc/sys/internal/logic/scopeservice"
	"zero-admin/rpc/sys/internal/svc"
	"zero-admin/rpc/sys/sysclient"
)

type ScopeServiceServer struct {
	svcCtx *svc.ServiceContext
	sysclient.UnimplementedScopeServiceServer
}

func NewScopeServiceServer(svcCtx *svc.ServiceContext) *ScopeServiceServer {
	return &ScopeServiceServer{
		svcCtx: svcCtx,
	}
}

// 安全范围管理
func (s *ScopeServiceServer) GetScopeList(ctx context.Context, in *sysclient.ScopeListRequest) (*sysclient.ScopeListResponse, error) {
	l := scopeservicelogic.NewGetScopeListLogic(ctx, s.svcCtx)
	return l.GetScopeList(in)
}

func (s *ScopeServiceServer) GetScopeById(ctx context.Context, in *sysclient.Int64Value) (*sysclient.Scope, error) {
	l := scopeservicelogic.NewGetScopeByIdLogic(ctx, s.svcCtx)
	return l.GetScopeById(in)
}

func (s *ScopeServiceServer) CreateScope(ctx context.Context, in *sysclient.CreateScopeRequest) (*sysclient.Scope, error) {
	l := scopeservicelogic.NewCreateScopeLogic(ctx, s.svcCtx)
	return l.CreateScope(in)
}

func (s *ScopeServiceServer) UpdateScope(ctx context.Context, in *sysclient.UpdateScopeRequest) (*sysclient.Scope, error) {
	l := scopeservicelogic.NewUpdateScopeLogic(ctx, s.svcCtx)
	return l.UpdateScope(in)
}

func (s *ScopeServiceServer) DeleteScope(ctx context.Context, in *sysclient.DeleteScopeRequest) (*sysclient.Empty, error) {
	l := scopeservicelogic.NewDeleteScopeLogic(ctx, s.svcCtx)
	return l.DeleteScope(in)
}

func (s *ScopeServiceServer) AddScopeMenus(ctx context.Context, in *sysclient.AddScopeMenusRequest) (*sysclient.ScopeInfo, error) {
	l := scopeservicelogic.NewAddScopeMenusLogic(ctx, s.svcCtx)
	return l.AddScopeMenus(in)
}

func (s *ScopeServiceServer) DeleteScopeMenus(ctx context.Context, in *sysclient.DeleteScopeMenusRequest) (*sysclient.ScopeInfo, error) {
	l := scopeservicelogic.NewDeleteScopeMenusLogic(ctx, s.svcCtx)
	return l.DeleteScopeMenus(in)
}

func (s *ScopeServiceServer) GetScopeMenus(ctx context.Context, in *sysclient.Int64Value) (*sysclient.ScopeInfo, error) {
	l := scopeservicelogic.NewGetScopeMenusLogic(ctx, s.svcCtx)
	return l.GetScopeMenus(in)
}

// 菜单管理
func (s *ScopeServiceServer) GetMenuTree(ctx context.Context, in *sysclient.MenuListRequest) (*sysclient.MenuTreeResponse, error) {
	l := scopeservicelogic.NewGetMenuTreeLogic(ctx, s.svcCtx)
	return l.GetMenuTree(in)
}

func (s *ScopeServiceServer) GetMenuById(ctx context.Context, in *sysclient.Int64Value) (*sysclient.Menu, error) {
	l := scopeservicelogic.NewGetMenuByIdLogic(ctx, s.svcCtx)
	return l.GetMenuById(in)
}

func (s *ScopeServiceServer) CreateMenu(ctx context.Context, in *sysclient.CreateMenuRequest) (*sysclient.Menu, error) {
	l := scopeservicelogic.NewCreateMenuLogic(ctx, s.svcCtx)
	return l.CreateMenu(in)
}

func (s *ScopeServiceServer) UpdateMenu(ctx context.Context, in *sysclient.UpdateMenuRequest) (*sysclient.Menu, error) {
	l := scopeservicelogic.NewUpdateMenuLogic(ctx, s.svcCtx)
	return l.UpdateMenu(in)
}

func (s *ScopeServiceServer) DeleteMenu(ctx context.Context, in *sysclient.DeleteMenuRequest) (*sysclient.Empty, error) {
	l := scopeservicelogic.NewDeleteMenuLogic(ctx, s.svcCtx)
	return l.DeleteMenu(in)
}
