// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: sys.proto

package operatelogservice

import (
	"context"

	"zero-admin/rpc/sys/sysclient"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddOperateLogReq           = sysclient.AddOperateLogReq
	AddOperateLogResp          = sysclient.AddOperateLogResp
	AddRolePermsRequest        = sysclient.AddRolePermsRequest
	AddScopeMenusRequest       = sysclient.AddScopeMenusRequest
	AssignUserRoleRequest      = sysclient.AssignUserRoleRequest
	BatchDeleteRolesRequest    = sysclient.BatchDeleteRolesRequest
	CreateMenuRequest          = sysclient.CreateMenuRequest
	CreateRoleRequest          = sysclient.CreateRoleRequest
	CreateScopeRequest         = sysclient.CreateScopeRequest
	CreateUserRequest          = sysclient.CreateUserRequest
	DeleteMenuRequest          = sysclient.DeleteMenuRequest
	DeleteOperateLogReq        = sysclient.DeleteOperateLogReq
	DeleteOperateLogResp       = sysclient.DeleteOperateLogResp
	DeleteRolePermsRequest     = sysclient.DeleteRolePermsRequest
	DeleteRoleRequest          = sysclient.DeleteRoleRequest
	DeleteScopeMenusRequest    = sysclient.DeleteScopeMenusRequest
	DeleteScopeRequest         = sysclient.DeleteScopeRequest
	DeleteUserRequest          = sysclient.DeleteUserRequest
	Empty                      = sysclient.Empty
	GetRoleByRoleCodesRequest  = sysclient.GetRoleByRoleCodesRequest
	GetRoleByRoleCodesResponse = sysclient.GetRoleByRoleCodesResponse
	GetRolePermsRequest        = sysclient.GetRolePermsRequest
	GetUserInfoRequest         = sysclient.GetUserInfoRequest
	Int64Value                 = sysclient.Int64Value
	LoginRequest               = sysclient.LoginRequest
	LoginResponse              = sysclient.LoginResponse
	Menu                       = sysclient.Menu
	MenuListRequest            = sysclient.MenuListRequest
	MenuTreeResponse           = sysclient.MenuTreeResponse
	OperateLog                 = sysclient.OperateLog
	OperateLogListData         = sysclient.OperateLogListData
	PageRequest                = sysclient.PageRequest
	PageResponse               = sysclient.PageResponse
	QueryOperateLogDetailReq   = sysclient.QueryOperateLogDetailReq
	QueryOperateLogListReq     = sysclient.QueryOperateLogListReq
	RefreshTokenRequest        = sysclient.RefreshTokenRequest
	RefreshTokenResponse       = sysclient.RefreshTokenResponse
	RegisterRequest            = sysclient.RegisterRequest
	RegisterResponse           = sysclient.RegisterResponse
	Role                       = sysclient.Role
	RoleInfo                   = sysclient.RoleInfo
	RoleListRequest            = sysclient.RoleListRequest
	RoleListResponse           = sysclient.RoleListResponse
	RoleScope                  = sysclient.RoleScope
	RoleScopeInfo              = sysclient.RoleScopeInfo
	Scope                      = sysclient.Scope
	ScopeInfo                  = sysclient.ScopeInfo
	ScopeListRequest           = sysclient.ScopeListRequest
	ScopeListResponse          = sysclient.ScopeListResponse
	ToggleRoleStatusRequest    = sysclient.ToggleRoleStatusRequest
	ToggleUserStatusRequest    = sysclient.ToggleUserStatusRequest
	UpdateMenuRequest          = sysclient.UpdateMenuRequest
	UpdatePasswordRequest      = sysclient.UpdatePasswordRequest
	UpdateRolePermsRequest     = sysclient.UpdateRolePermsRequest
	UpdateRoleRequest          = sysclient.UpdateRoleRequest
	UpdateScopeRequest         = sysclient.UpdateScopeRequest
	UpdateUserPasswordRequest  = sysclient.UpdateUserPasswordRequest
	UpdateUserRequest          = sysclient.UpdateUserRequest
	User                       = sysclient.User
	UserInfo                   = sysclient.UserInfo
	UserListRequest            = sysclient.UserListRequest
	UserListResponse           = sysclient.UserListResponse

	OperateLogService interface {
		// 添加系统操作日志表
		AddOperateLog(ctx context.Context, in *AddOperateLogReq, opts ...grpc.CallOption) (*AddOperateLogResp, error)
		// 删除系统操作日志表
		DeleteOperateLog(ctx context.Context, in *DeleteOperateLogReq, opts ...grpc.CallOption) (*DeleteOperateLogResp, error)
		// 查询系统操作日志表详情
		QueryOperateLogDetail(ctx context.Context, in *QueryOperateLogDetailReq, opts ...grpc.CallOption) (*OperateLog, error)
		// 查询系统操作日志表列表
		QueryOperateLogList(ctx context.Context, in *QueryOperateLogListReq, opts ...grpc.CallOption) (*OperateLogListData, error)
	}

	defaultOperateLogService struct {
		cli zrpc.Client
	}
)

func NewOperateLogService(cli zrpc.Client) OperateLogService {
	return &defaultOperateLogService{
		cli: cli,
	}
}

// 添加系统操作日志表
func (m *defaultOperateLogService) AddOperateLog(ctx context.Context, in *AddOperateLogReq, opts ...grpc.CallOption) (*AddOperateLogResp, error) {
	client := sysclient.NewOperateLogServiceClient(m.cli.Conn())
	return client.AddOperateLog(ctx, in, opts...)
}

// 删除系统操作日志表
func (m *defaultOperateLogService) DeleteOperateLog(ctx context.Context, in *DeleteOperateLogReq, opts ...grpc.CallOption) (*DeleteOperateLogResp, error) {
	client := sysclient.NewOperateLogServiceClient(m.cli.Conn())
	return client.DeleteOperateLog(ctx, in, opts...)
}

// 查询系统操作日志表详情
func (m *defaultOperateLogService) QueryOperateLogDetail(ctx context.Context, in *QueryOperateLogDetailReq, opts ...grpc.CallOption) (*OperateLog, error) {
	client := sysclient.NewOperateLogServiceClient(m.cli.Conn())
	return client.QueryOperateLogDetail(ctx, in, opts...)
}

// 查询系统操作日志表列表
func (m *defaultOperateLogService) QueryOperateLogList(ctx context.Context, in *QueryOperateLogListReq, opts ...grpc.CallOption) (*OperateLogListData, error) {
	client := sysclient.NewOperateLogServiceClient(m.cli.Conn())
	return client.QueryOperateLogList(ctx, in, opts...)
}
