// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"zero-admin/rpc/sys/db/mysql/model"
)

func newSysScope(db *gorm.DB, opts ...gen.DOOption) sysScope {
	_sysScope := sysScope{}

	_sysScope.sysScopeDo.UseDB(db, opts...)
	_sysScope.sysScopeDo.UseModel(&model.SysScope{})

	tableName := _sysScope.sysScopeDo.TableName()
	_sysScope.ALL = field.NewAsterisk(tableName)
	_sysScope.ID = field.NewInt64(tableName, "id")
	_sysScope.ScopeName = field.NewString(tableName, "scope_name")
	_sysScope.ScopeCode = field.NewString(tableName, "scope_code")
	_sysScope.Description = field.NewString(tableName, "description")
	_sysScope.Sort = field.NewInt32(tableName, "sort")
	_sysScope.Status = field.NewInt32(tableName, "status")
	_sysScope.Creator = field.NewString(tableName, "creator")
	_sysScope.CreateTime = field.NewTime(tableName, "create_time")
	_sysScope.Updater = field.NewString(tableName, "updater")
	_sysScope.UpdateTime = field.NewTime(tableName, "update_time")
	_sysScope.DelFlag = field.NewInt32(tableName, "del_flag")

	_sysScope.fillFieldMap()

	return _sysScope
}

// sysScope 系统安全范围表
type sysScope struct {
	sysScopeDo sysScopeDo

	ALL         field.Asterisk
	ID          field.Int64  // 范围ID
	ScopeName   field.String // 范围名称
	ScopeCode   field.String // 范围编码
	Description field.String // 范围描述
	Sort        field.Int32  // 排序
	Status      field.Int32  // 0-禁用 1-启用
	Creator     field.String // 创建人
	CreateTime  field.Time   // 创建时间
	Updater     field.String // 更新人
	UpdateTime  field.Time   // 更新时间
	DelFlag     field.Int32  // 删除标记（0-未删除，1-已删除）

	fieldMap map[string]field.Expr
}

func (s sysScope) Table(newTableName string) *sysScope {
	s.sysScopeDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sysScope) As(alias string) *sysScope {
	s.sysScopeDo.DO = *(s.sysScopeDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sysScope) updateTableName(table string) *sysScope {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt64(table, "id")
	s.ScopeName = field.NewString(table, "scope_name")
	s.ScopeCode = field.NewString(table, "scope_code")
	s.Description = field.NewString(table, "description")
	s.Sort = field.NewInt32(table, "sort")
	s.Status = field.NewInt32(table, "status")
	s.Creator = field.NewString(table, "creator")
	s.CreateTime = field.NewTime(table, "create_time")
	s.Updater = field.NewString(table, "updater")
	s.UpdateTime = field.NewTime(table, "update_time")
	s.DelFlag = field.NewInt32(table, "del_flag")

	s.fillFieldMap()

	return s
}

func (s *sysScope) WithContext(ctx context.Context) ISysScopeDo { return s.sysScopeDo.WithContext(ctx) }

func (s sysScope) TableName() string { return s.sysScopeDo.TableName() }

func (s sysScope) Alias() string { return s.sysScopeDo.Alias() }

func (s sysScope) Columns(cols ...field.Expr) gen.Columns { return s.sysScopeDo.Columns(cols...) }

func (s *sysScope) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sysScope) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 11)
	s.fieldMap["id"] = s.ID
	s.fieldMap["scope_name"] = s.ScopeName
	s.fieldMap["scope_code"] = s.ScopeCode
	s.fieldMap["description"] = s.Description
	s.fieldMap["sort"] = s.Sort
	s.fieldMap["status"] = s.Status
	s.fieldMap["creator"] = s.Creator
	s.fieldMap["create_time"] = s.CreateTime
	s.fieldMap["updater"] = s.Updater
	s.fieldMap["update_time"] = s.UpdateTime
	s.fieldMap["del_flag"] = s.DelFlag
}

func (s sysScope) clone(db *gorm.DB) sysScope {
	s.sysScopeDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s sysScope) replaceDB(db *gorm.DB) sysScope {
	s.sysScopeDo.ReplaceDB(db)
	return s
}

type sysScopeDo struct{ gen.DO }

type ISysScopeDo interface {
	gen.SubQuery
	Debug() ISysScopeDo
	WithContext(ctx context.Context) ISysScopeDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISysScopeDo
	WriteDB() ISysScopeDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISysScopeDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISysScopeDo
	Not(conds ...gen.Condition) ISysScopeDo
	Or(conds ...gen.Condition) ISysScopeDo
	Select(conds ...field.Expr) ISysScopeDo
	Where(conds ...gen.Condition) ISysScopeDo
	Order(conds ...field.Expr) ISysScopeDo
	Distinct(cols ...field.Expr) ISysScopeDo
	Omit(cols ...field.Expr) ISysScopeDo
	Join(table schema.Tabler, on ...field.Expr) ISysScopeDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISysScopeDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISysScopeDo
	Group(cols ...field.Expr) ISysScopeDo
	Having(conds ...gen.Condition) ISysScopeDo
	Limit(limit int) ISysScopeDo
	Offset(offset int) ISysScopeDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISysScopeDo
	Unscoped() ISysScopeDo
	Create(values ...*model.SysScope) error
	CreateInBatches(values []*model.SysScope, batchSize int) error
	Save(values ...*model.SysScope) error
	First() (*model.SysScope, error)
	Take() (*model.SysScope, error)
	Last() (*model.SysScope, error)
	Find() ([]*model.SysScope, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SysScope, err error)
	FindInBatches(result *[]*model.SysScope, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.SysScope) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISysScopeDo
	Assign(attrs ...field.AssignExpr) ISysScopeDo
	Joins(fields ...field.RelationField) ISysScopeDo
	Preload(fields ...field.RelationField) ISysScopeDo
	FirstOrInit() (*model.SysScope, error)
	FirstOrCreate() (*model.SysScope, error)
	FindByPage(offset int, limit int) (result []*model.SysScope, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISysScopeDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s sysScopeDo) Debug() ISysScopeDo {
	return s.withDO(s.DO.Debug())
}

func (s sysScopeDo) WithContext(ctx context.Context) ISysScopeDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sysScopeDo) ReadDB() ISysScopeDo {
	return s.Clauses(dbresolver.Read)
}

func (s sysScopeDo) WriteDB() ISysScopeDo {
	return s.Clauses(dbresolver.Write)
}

func (s sysScopeDo) Session(config *gorm.Session) ISysScopeDo {
	return s.withDO(s.DO.Session(config))
}

func (s sysScopeDo) Clauses(conds ...clause.Expression) ISysScopeDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sysScopeDo) Returning(value interface{}, columns ...string) ISysScopeDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sysScopeDo) Not(conds ...gen.Condition) ISysScopeDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sysScopeDo) Or(conds ...gen.Condition) ISysScopeDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sysScopeDo) Select(conds ...field.Expr) ISysScopeDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sysScopeDo) Where(conds ...gen.Condition) ISysScopeDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sysScopeDo) Order(conds ...field.Expr) ISysScopeDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sysScopeDo) Distinct(cols ...field.Expr) ISysScopeDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sysScopeDo) Omit(cols ...field.Expr) ISysScopeDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sysScopeDo) Join(table schema.Tabler, on ...field.Expr) ISysScopeDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sysScopeDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISysScopeDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sysScopeDo) RightJoin(table schema.Tabler, on ...field.Expr) ISysScopeDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sysScopeDo) Group(cols ...field.Expr) ISysScopeDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sysScopeDo) Having(conds ...gen.Condition) ISysScopeDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sysScopeDo) Limit(limit int) ISysScopeDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sysScopeDo) Offset(offset int) ISysScopeDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sysScopeDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISysScopeDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sysScopeDo) Unscoped() ISysScopeDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sysScopeDo) Create(values ...*model.SysScope) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sysScopeDo) CreateInBatches(values []*model.SysScope, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sysScopeDo) Save(values ...*model.SysScope) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sysScopeDo) First() (*model.SysScope, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysScope), nil
	}
}

func (s sysScopeDo) Take() (*model.SysScope, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysScope), nil
	}
}

func (s sysScopeDo) Last() (*model.SysScope, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysScope), nil
	}
}

func (s sysScopeDo) Find() ([]*model.SysScope, error) {
	result, err := s.DO.Find()
	return result.([]*model.SysScope), err
}

func (s sysScopeDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SysScope, err error) {
	buf := make([]*model.SysScope, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sysScopeDo) FindInBatches(result *[]*model.SysScope, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sysScopeDo) Attrs(attrs ...field.AssignExpr) ISysScopeDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sysScopeDo) Assign(attrs ...field.AssignExpr) ISysScopeDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sysScopeDo) Joins(fields ...field.RelationField) ISysScopeDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sysScopeDo) Preload(fields ...field.RelationField) ISysScopeDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sysScopeDo) FirstOrInit() (*model.SysScope, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysScope), nil
	}
}

func (s sysScopeDo) FirstOrCreate() (*model.SysScope, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysScope), nil
	}
}

func (s sysScopeDo) FindByPage(offset int, limit int) (result []*model.SysScope, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sysScopeDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sysScopeDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sysScopeDo) Delete(models ...*model.SysScope) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sysScopeDo) withDO(do gen.Dao) *sysScopeDo {
	s.DO = *do.(*gen.DO)
	return s
}
