// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"zero-admin/rpc/sys/db/mysql/model"
)

func newSysRoleScope(db *gorm.DB, opts ...gen.DOOption) sysRoleScope {
	_sysRoleScope := sysRoleScope{}

	_sysRoleScope.sysRoleScopeDo.UseDB(db, opts...)
	_sysRoleScope.sysRoleScopeDo.UseModel(&model.SysRoleScope{})

	tableName := _sysRoleScope.sysRoleScopeDo.TableName()
	_sysRoleScope.ALL = field.NewAsterisk(tableName)
	_sysRoleScope.ID = field.NewInt64(tableName, "id")
	_sysRoleScope.RoleCode = field.NewString(tableName, "role_code")
	_sysRoleScope.ScopeCode = field.NewString(tableName, "scope_code")
	_sysRoleScope.Perm = field.NewInt32(tableName, "perm")
	_sysRoleScope.CreateTime = field.NewTime(tableName, "create_time")

	_sysRoleScope.fillFieldMap()

	return _sysRoleScope
}

// sysRoleScope 系统角色-安全范围关联表
type sysRoleScope struct {
	sysRoleScopeDo sysRoleScopeDo

	ALL        field.Asterisk
	ID         field.Int64  // 关联ID
	RoleCode   field.String // 角色
	ScopeCode  field.String // 范围
	Perm       field.Int32  // 权限（0-无权限，1-读，2-写，4-创建，8-删除）
	CreateTime field.Time   // 创建时间

	fieldMap map[string]field.Expr
}

func (s sysRoleScope) Table(newTableName string) *sysRoleScope {
	s.sysRoleScopeDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sysRoleScope) As(alias string) *sysRoleScope {
	s.sysRoleScopeDo.DO = *(s.sysRoleScopeDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sysRoleScope) updateTableName(table string) *sysRoleScope {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt64(table, "id")
	s.RoleCode = field.NewString(table, "role_code")
	s.ScopeCode = field.NewString(table, "scope_code")
	s.Perm = field.NewInt32(table, "perm")
	s.CreateTime = field.NewTime(table, "create_time")

	s.fillFieldMap()

	return s
}

func (s *sysRoleScope) WithContext(ctx context.Context) ISysRoleScopeDo {
	return s.sysRoleScopeDo.WithContext(ctx)
}

func (s sysRoleScope) TableName() string { return s.sysRoleScopeDo.TableName() }

func (s sysRoleScope) Alias() string { return s.sysRoleScopeDo.Alias() }

func (s sysRoleScope) Columns(cols ...field.Expr) gen.Columns {
	return s.sysRoleScopeDo.Columns(cols...)
}

func (s *sysRoleScope) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sysRoleScope) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 5)
	s.fieldMap["id"] = s.ID
	s.fieldMap["role_code"] = s.RoleCode
	s.fieldMap["scope_code"] = s.ScopeCode
	s.fieldMap["perm"] = s.Perm
	s.fieldMap["create_time"] = s.CreateTime
}

func (s sysRoleScope) clone(db *gorm.DB) sysRoleScope {
	s.sysRoleScopeDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s sysRoleScope) replaceDB(db *gorm.DB) sysRoleScope {
	s.sysRoleScopeDo.ReplaceDB(db)
	return s
}

type sysRoleScopeDo struct{ gen.DO }

type ISysRoleScopeDo interface {
	gen.SubQuery
	Debug() ISysRoleScopeDo
	WithContext(ctx context.Context) ISysRoleScopeDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISysRoleScopeDo
	WriteDB() ISysRoleScopeDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISysRoleScopeDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISysRoleScopeDo
	Not(conds ...gen.Condition) ISysRoleScopeDo
	Or(conds ...gen.Condition) ISysRoleScopeDo
	Select(conds ...field.Expr) ISysRoleScopeDo
	Where(conds ...gen.Condition) ISysRoleScopeDo
	Order(conds ...field.Expr) ISysRoleScopeDo
	Distinct(cols ...field.Expr) ISysRoleScopeDo
	Omit(cols ...field.Expr) ISysRoleScopeDo
	Join(table schema.Tabler, on ...field.Expr) ISysRoleScopeDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISysRoleScopeDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISysRoleScopeDo
	Group(cols ...field.Expr) ISysRoleScopeDo
	Having(conds ...gen.Condition) ISysRoleScopeDo
	Limit(limit int) ISysRoleScopeDo
	Offset(offset int) ISysRoleScopeDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISysRoleScopeDo
	Unscoped() ISysRoleScopeDo
	Create(values ...*model.SysRoleScope) error
	CreateInBatches(values []*model.SysRoleScope, batchSize int) error
	Save(values ...*model.SysRoleScope) error
	First() (*model.SysRoleScope, error)
	Take() (*model.SysRoleScope, error)
	Last() (*model.SysRoleScope, error)
	Find() ([]*model.SysRoleScope, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SysRoleScope, err error)
	FindInBatches(result *[]*model.SysRoleScope, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.SysRoleScope) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISysRoleScopeDo
	Assign(attrs ...field.AssignExpr) ISysRoleScopeDo
	Joins(fields ...field.RelationField) ISysRoleScopeDo
	Preload(fields ...field.RelationField) ISysRoleScopeDo
	FirstOrInit() (*model.SysRoleScope, error)
	FirstOrCreate() (*model.SysRoleScope, error)
	FindByPage(offset int, limit int) (result []*model.SysRoleScope, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISysRoleScopeDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s sysRoleScopeDo) Debug() ISysRoleScopeDo {
	return s.withDO(s.DO.Debug())
}

func (s sysRoleScopeDo) WithContext(ctx context.Context) ISysRoleScopeDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sysRoleScopeDo) ReadDB() ISysRoleScopeDo {
	return s.Clauses(dbresolver.Read)
}

func (s sysRoleScopeDo) WriteDB() ISysRoleScopeDo {
	return s.Clauses(dbresolver.Write)
}

func (s sysRoleScopeDo) Session(config *gorm.Session) ISysRoleScopeDo {
	return s.withDO(s.DO.Session(config))
}

func (s sysRoleScopeDo) Clauses(conds ...clause.Expression) ISysRoleScopeDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sysRoleScopeDo) Returning(value interface{}, columns ...string) ISysRoleScopeDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sysRoleScopeDo) Not(conds ...gen.Condition) ISysRoleScopeDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sysRoleScopeDo) Or(conds ...gen.Condition) ISysRoleScopeDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sysRoleScopeDo) Select(conds ...field.Expr) ISysRoleScopeDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sysRoleScopeDo) Where(conds ...gen.Condition) ISysRoleScopeDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sysRoleScopeDo) Order(conds ...field.Expr) ISysRoleScopeDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sysRoleScopeDo) Distinct(cols ...field.Expr) ISysRoleScopeDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sysRoleScopeDo) Omit(cols ...field.Expr) ISysRoleScopeDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sysRoleScopeDo) Join(table schema.Tabler, on ...field.Expr) ISysRoleScopeDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sysRoleScopeDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISysRoleScopeDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sysRoleScopeDo) RightJoin(table schema.Tabler, on ...field.Expr) ISysRoleScopeDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sysRoleScopeDo) Group(cols ...field.Expr) ISysRoleScopeDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sysRoleScopeDo) Having(conds ...gen.Condition) ISysRoleScopeDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sysRoleScopeDo) Limit(limit int) ISysRoleScopeDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sysRoleScopeDo) Offset(offset int) ISysRoleScopeDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sysRoleScopeDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISysRoleScopeDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sysRoleScopeDo) Unscoped() ISysRoleScopeDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sysRoleScopeDo) Create(values ...*model.SysRoleScope) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sysRoleScopeDo) CreateInBatches(values []*model.SysRoleScope, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sysRoleScopeDo) Save(values ...*model.SysRoleScope) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sysRoleScopeDo) First() (*model.SysRoleScope, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysRoleScope), nil
	}
}

func (s sysRoleScopeDo) Take() (*model.SysRoleScope, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysRoleScope), nil
	}
}

func (s sysRoleScopeDo) Last() (*model.SysRoleScope, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysRoleScope), nil
	}
}

func (s sysRoleScopeDo) Find() ([]*model.SysRoleScope, error) {
	result, err := s.DO.Find()
	return result.([]*model.SysRoleScope), err
}

func (s sysRoleScopeDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SysRoleScope, err error) {
	buf := make([]*model.SysRoleScope, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sysRoleScopeDo) FindInBatches(result *[]*model.SysRoleScope, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sysRoleScopeDo) Attrs(attrs ...field.AssignExpr) ISysRoleScopeDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sysRoleScopeDo) Assign(attrs ...field.AssignExpr) ISysRoleScopeDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sysRoleScopeDo) Joins(fields ...field.RelationField) ISysRoleScopeDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sysRoleScopeDo) Preload(fields ...field.RelationField) ISysRoleScopeDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sysRoleScopeDo) FirstOrInit() (*model.SysRoleScope, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysRoleScope), nil
	}
}

func (s sysRoleScopeDo) FirstOrCreate() (*model.SysRoleScope, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysRoleScope), nil
	}
}

func (s sysRoleScopeDo) FindByPage(offset int, limit int) (result []*model.SysRoleScope, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sysRoleScopeDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sysRoleScopeDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sysRoleScopeDo) Delete(models ...*model.SysRoleScope) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sysRoleScopeDo) withDO(do gen.Dao) *sysRoleScopeDo {
	s.DO = *do.(*gen.DO)
	return s
}
