// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: sys.proto

package server

import (
	"context"

	"zero-admin/rpc/sys/internal/logic/roleservice"
	"zero-admin/rpc/sys/internal/svc"
	"zero-admin/rpc/sys/sysclient"
)

type RoleServiceServer struct {
	svcCtx *svc.ServiceContext
	sysclient.UnimplementedRoleServiceServer
}

func NewRoleServiceServer(svcCtx *svc.ServiceContext) *RoleServiceServer {
	return &RoleServiceServer{
		svcCtx: svcCtx,
	}
}

// 全部角色
func (s *RoleServiceServer) GetAllRoles(ctx context.Context, in *sysclient.GetAllRolesRequest) (*sysclient.GetAllRolesResponse, error) {
	l := roleservicelogic.NewGetAllRolesLogic(ctx, s.svcCtx)
	return l.GetAllRoles(in)
}

// 角色列表
func (s *RoleServiceServer) GetRoleList(ctx context.Context, in *sysclient.RoleListRequest) (*sysclient.RoleListResponse, error) {
	l := roleservicelogic.NewGetRoleListLogic(ctx, s.svcCtx)
	return l.GetRoleList(in)
}

// 创建角色
func (s *RoleServiceServer) CreateRole(ctx context.Context, in *sysclient.CreateRoleRequest) (*sysclient.Role, error) {
	l := roleservicelogic.NewCreateRoleLogic(ctx, s.svcCtx)
	return l.CreateRole(in)
}

// 更新角色
func (s *RoleServiceServer) UpdateRole(ctx context.Context, in *sysclient.UpdateRoleRequest) (*sysclient.Role, error) {
	l := roleservicelogic.NewUpdateRoleLogic(ctx, s.svcCtx)
	return l.UpdateRole(in)
}

// 禁用角色
func (s *RoleServiceServer) ToggleRoleStatus(ctx context.Context, in *sysclient.ToggleRoleStatusRequest) (*sysclient.Role, error) {
	l := roleservicelogic.NewToggleRoleStatusLogic(ctx, s.svcCtx)
	return l.ToggleRoleStatus(in)
}

// 删除角色
func (s *RoleServiceServer) DeleteRole(ctx context.Context, in *sysclient.DeleteRoleRequest) (*sysclient.Empty, error) {
	l := roleservicelogic.NewDeleteRoleLogic(ctx, s.svcCtx)
	return l.DeleteRole(in)
}

func (s *RoleServiceServer) BatchDeleteRoles(ctx context.Context, in *sysclient.BatchDeleteRolesRequest) (*sysclient.Empty, error) {
	l := roleservicelogic.NewBatchDeleteRolesLogic(ctx, s.svcCtx)
	return l.BatchDeleteRoles(in)
}

// 添加角色权限
func (s *RoleServiceServer) AddRolePerms(ctx context.Context, in *sysclient.AddRolePermsRequest) (*sysclient.RoleInfo, error) {
	l := roleservicelogic.NewAddRolePermsLogic(ctx, s.svcCtx)
	return l.AddRolePerms(in)
}

// 更新角色权限
func (s *RoleServiceServer) UpdateRolePerms(ctx context.Context, in *sysclient.UpdateRolePermsRequest) (*sysclient.RoleInfo, error) {
	l := roleservicelogic.NewUpdateRolePermsLogic(ctx, s.svcCtx)
	return l.UpdateRolePerms(in)
}

// 删除角色权限
func (s *RoleServiceServer) DeleteRolePerms(ctx context.Context, in *sysclient.DeleteRolePermsRequest) (*sysclient.RoleInfo, error) {
	l := roleservicelogic.NewDeleteRolePermsLogic(ctx, s.svcCtx)
	return l.DeleteRolePerms(in)
}

// 获取角色权限
func (s *RoleServiceServer) GetRolePerms(ctx context.Context, in *sysclient.GetRolePermsRequest) (*sysclient.RoleInfo, error) {
	l := roleservicelogic.NewGetRolePermsLogic(ctx, s.svcCtx)
	return l.GetRolePerms(in)
}

// 获取关联给定安全范围的角色
func (s *RoleServiceServer) GetRoleListByScopeCode(ctx context.Context, in *sysclient.GetRolesByScopeCodeRequest) (*sysclient.GetRoleByRoleCodesResponse, error) {
	l := roleservicelogic.NewGetRoleListByScopeCodeLogic(ctx, s.svcCtx)
	return l.GetRoleListByScopeCode(in)
}
