// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: sys.proto

package server

import (
	"context"

	"zero-admin/rpc/sys/internal/logic/roleservice"
	"zero-admin/rpc/sys/internal/svc"
	"zero-admin/rpc/sys/sysclient"
)

type RoleServiceServer struct {
	svcCtx *svc.ServiceContext
	sysclient.UnimplementedRoleServiceServer
}

func NewRoleServiceServer(svcCtx *svc.ServiceContext) *RoleServiceServer {
	return &RoleServiceServer{
		svcCtx: svcCtx,
	}
}

// 角色管理
func (s *RoleServiceServer) GetRoleList(ctx context.Context, in *sysclient.RoleListRequest) (*sysclient.RoleListResponse, error) {
	l := roleservicelogic.NewGetRoleListLogic(ctx, s.svcCtx)
	return l.GetRoleList(in)
}

func (s *RoleServiceServer) GetRoleById(ctx context.Context, in *sysclient.Int64Value) (*sysclient.RoleInfo, error) {
	l := roleservicelogic.NewGetRoleByIdLogic(ctx, s.svcCtx)
	return l.GetRoleById(in)
}

func (s *RoleServiceServer) CreateRole(ctx context.Context, in *sysclient.CreateRoleRequest) (*sysclient.RoleInfo, error) {
	l := roleservicelogic.NewCreateRoleLogic(ctx, s.svcCtx)
	return l.CreateRole(in)
}

func (s *RoleServiceServer) UpdateRole(ctx context.Context, in *sysclient.UpdateRoleRequest) (*sysclient.RoleInfo, error) {
	l := roleservicelogic.NewUpdateRoleLogic(ctx, s.svcCtx)
	return l.UpdateRole(in)
}

func (s *RoleServiceServer) UpdateRoleScopes(ctx context.Context, in *sysclient.UpdateRoleScopesRequest) (*sysclient.RoleScope, error) {
	l := roleservicelogic.NewUpdateRoleScopesLogic(ctx, s.svcCtx)
	return l.UpdateRoleScopes(in)
}

func (s *RoleServiceServer) DeleteRole(ctx context.Context, in *sysclient.DeleteRoleRequest) (*sysclient.Empty, error) {
	l := roleservicelogic.NewDeleteRoleLogic(ctx, s.svcCtx)
	return l.DeleteRole(in)
}
