// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: sys.proto

package scopeservice

import (
	"context"

	"zero-admin/rpc/sys/sysclient"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddOperateLogReq           = sysclient.AddOperateLogReq
	AddOperateLogResp          = sysclient.AddOperateLogResp
	AddRolePermsRequest        = sysclient.AddRolePermsRequest
	AddScopeMenusRequest       = sysclient.AddScopeMenusRequest
	AssignUserRoleRequest      = sysclient.AssignUserRoleRequest
	BatchDeleteRolesRequest    = sysclient.BatchDeleteRolesRequest
	CreateMenuRequest          = sysclient.CreateMenuRequest
	CreateRoleRequest          = sysclient.CreateRoleRequest
	CreateScopeRequest         = sysclient.CreateScopeRequest
	CreateUserRequest          = sysclient.CreateUserRequest
	DeleteMenuRequest          = sysclient.DeleteMenuRequest
	DeleteOperateLogReq        = sysclient.DeleteOperateLogReq
	DeleteOperateLogResp       = sysclient.DeleteOperateLogResp
	DeleteRolePermsRequest     = sysclient.DeleteRolePermsRequest
	DeleteRoleRequest          = sysclient.DeleteRoleRequest
	DeleteScopeMenusRequest    = sysclient.DeleteScopeMenusRequest
	DeleteScopeRequest         = sysclient.DeleteScopeRequest
	DeleteUserRequest          = sysclient.DeleteUserRequest
	Empty                      = sysclient.Empty
	GetAllRolesRequest         = sysclient.GetAllRolesRequest
	GetAllRolesResponse        = sysclient.GetAllRolesResponse
	GetAllScopesResponse       = sysclient.GetAllScopesResponse
	GetRoleByRoleCodesRequest  = sysclient.GetRoleByRoleCodesRequest
	GetRoleByRoleCodesResponse = sysclient.GetRoleByRoleCodesResponse
	GetRolePermsRequest        = sysclient.GetRolePermsRequest
	GetUserInfoRequest         = sysclient.GetUserInfoRequest
	Int64Value                 = sysclient.Int64Value
	LoginRequest               = sysclient.LoginRequest
	LoginResponse              = sysclient.LoginResponse
	Menu                       = sysclient.Menu
	MenuListRequest            = sysclient.MenuListRequest
	MenuTreeResponse           = sysclient.MenuTreeResponse
	OperateLog                 = sysclient.OperateLog
	OperateLogListData         = sysclient.OperateLogListData
	PageRequest                = sysclient.PageRequest
	PageResponse               = sysclient.PageResponse
	QueryOperateLogDetailReq   = sysclient.QueryOperateLogDetailReq
	QueryOperateLogListReq     = sysclient.QueryOperateLogListReq
	RefreshTokenRequest        = sysclient.RefreshTokenRequest
	RefreshTokenResponse       = sysclient.RefreshTokenResponse
	RegisterRequest            = sysclient.RegisterRequest
	RegisterResponse           = sysclient.RegisterResponse
	Role                       = sysclient.Role
	RoleInfo                   = sysclient.RoleInfo
	RoleListRequest            = sysclient.RoleListRequest
	RoleListResponse           = sysclient.RoleListResponse
	RoleScope                  = sysclient.RoleScope
	RoleScopeInfo              = sysclient.RoleScopeInfo
	Scope                      = sysclient.Scope
	ScopeInfo                  = sysclient.ScopeInfo
	ScopeListRequest           = sysclient.ScopeListRequest
	ScopeListResponse          = sysclient.ScopeListResponse
	ToggleRoleStatusRequest    = sysclient.ToggleRoleStatusRequest
	ToggleUserStatusRequest    = sysclient.ToggleUserStatusRequest
	UpdateMenuRequest          = sysclient.UpdateMenuRequest
	UpdatePasswordRequest      = sysclient.UpdatePasswordRequest
	UpdateRolePermsRequest     = sysclient.UpdateRolePermsRequest
	UpdateRoleRequest          = sysclient.UpdateRoleRequest
	UpdateScopeRequest         = sysclient.UpdateScopeRequest
	UpdateUserPasswordRequest  = sysclient.UpdateUserPasswordRequest
	UpdateUserRequest          = sysclient.UpdateUserRequest
	User                       = sysclient.User
	UserInfo                   = sysclient.UserInfo
	UserListRequest            = sysclient.UserListRequest
	UserListResponse           = sysclient.UserListResponse

	ScopeService interface {
		// 安全范围管理
		GetAllScopes(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetAllScopesResponse, error)
		GetScopeList(ctx context.Context, in *ScopeListRequest, opts ...grpc.CallOption) (*ScopeListResponse, error)
		GetScopeById(ctx context.Context, in *Int64Value, opts ...grpc.CallOption) (*Scope, error)
		CreateScope(ctx context.Context, in *CreateScopeRequest, opts ...grpc.CallOption) (*Scope, error)
		UpdateScope(ctx context.Context, in *UpdateScopeRequest, opts ...grpc.CallOption) (*Scope, error)
		DeleteScope(ctx context.Context, in *DeleteScopeRequest, opts ...grpc.CallOption) (*Empty, error)
		AddScopeMenus(ctx context.Context, in *AddScopeMenusRequest, opts ...grpc.CallOption) (*ScopeInfo, error)
		DeleteScopeMenus(ctx context.Context, in *DeleteScopeMenusRequest, opts ...grpc.CallOption) (*ScopeInfo, error)
		GetScopeMenus(ctx context.Context, in *Int64Value, opts ...grpc.CallOption) (*ScopeInfo, error)
		// 菜单管理
		GetMenuTree(ctx context.Context, in *MenuListRequest, opts ...grpc.CallOption) (*MenuTreeResponse, error)
		GetMenuById(ctx context.Context, in *Int64Value, opts ...grpc.CallOption) (*Menu, error)
		CreateMenu(ctx context.Context, in *CreateMenuRequest, opts ...grpc.CallOption) (*Menu, error)
		UpdateMenu(ctx context.Context, in *UpdateMenuRequest, opts ...grpc.CallOption) (*Menu, error)
		DeleteMenu(ctx context.Context, in *DeleteMenuRequest, opts ...grpc.CallOption) (*Empty, error)
	}

	defaultScopeService struct {
		cli zrpc.Client
	}
)

func NewScopeService(cli zrpc.Client) ScopeService {
	return &defaultScopeService{
		cli: cli,
	}
}

// 安全范围管理
func (m *defaultScopeService) GetAllScopes(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetAllScopesResponse, error) {
	client := sysclient.NewScopeServiceClient(m.cli.Conn())
	return client.GetAllScopes(ctx, in, opts...)
}

func (m *defaultScopeService) GetScopeList(ctx context.Context, in *ScopeListRequest, opts ...grpc.CallOption) (*ScopeListResponse, error) {
	client := sysclient.NewScopeServiceClient(m.cli.Conn())
	return client.GetScopeList(ctx, in, opts...)
}

func (m *defaultScopeService) GetScopeById(ctx context.Context, in *Int64Value, opts ...grpc.CallOption) (*Scope, error) {
	client := sysclient.NewScopeServiceClient(m.cli.Conn())
	return client.GetScopeById(ctx, in, opts...)
}

func (m *defaultScopeService) CreateScope(ctx context.Context, in *CreateScopeRequest, opts ...grpc.CallOption) (*Scope, error) {
	client := sysclient.NewScopeServiceClient(m.cli.Conn())
	return client.CreateScope(ctx, in, opts...)
}

func (m *defaultScopeService) UpdateScope(ctx context.Context, in *UpdateScopeRequest, opts ...grpc.CallOption) (*Scope, error) {
	client := sysclient.NewScopeServiceClient(m.cli.Conn())
	return client.UpdateScope(ctx, in, opts...)
}

func (m *defaultScopeService) DeleteScope(ctx context.Context, in *DeleteScopeRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := sysclient.NewScopeServiceClient(m.cli.Conn())
	return client.DeleteScope(ctx, in, opts...)
}

func (m *defaultScopeService) AddScopeMenus(ctx context.Context, in *AddScopeMenusRequest, opts ...grpc.CallOption) (*ScopeInfo, error) {
	client := sysclient.NewScopeServiceClient(m.cli.Conn())
	return client.AddScopeMenus(ctx, in, opts...)
}

func (m *defaultScopeService) DeleteScopeMenus(ctx context.Context, in *DeleteScopeMenusRequest, opts ...grpc.CallOption) (*ScopeInfo, error) {
	client := sysclient.NewScopeServiceClient(m.cli.Conn())
	return client.DeleteScopeMenus(ctx, in, opts...)
}

func (m *defaultScopeService) GetScopeMenus(ctx context.Context, in *Int64Value, opts ...grpc.CallOption) (*ScopeInfo, error) {
	client := sysclient.NewScopeServiceClient(m.cli.Conn())
	return client.GetScopeMenus(ctx, in, opts...)
}

// 菜单管理
func (m *defaultScopeService) GetMenuTree(ctx context.Context, in *MenuListRequest, opts ...grpc.CallOption) (*MenuTreeResponse, error) {
	client := sysclient.NewScopeServiceClient(m.cli.Conn())
	return client.GetMenuTree(ctx, in, opts...)
}

func (m *defaultScopeService) GetMenuById(ctx context.Context, in *Int64Value, opts ...grpc.CallOption) (*Menu, error) {
	client := sysclient.NewScopeServiceClient(m.cli.Conn())
	return client.GetMenuById(ctx, in, opts...)
}

func (m *defaultScopeService) CreateMenu(ctx context.Context, in *CreateMenuRequest, opts ...grpc.CallOption) (*Menu, error) {
	client := sysclient.NewScopeServiceClient(m.cli.Conn())
	return client.CreateMenu(ctx, in, opts...)
}

func (m *defaultScopeService) UpdateMenu(ctx context.Context, in *UpdateMenuRequest, opts ...grpc.CallOption) (*Menu, error) {
	client := sysclient.NewScopeServiceClient(m.cli.Conn())
	return client.UpdateMenu(ctx, in, opts...)
}

func (m *defaultScopeService) DeleteMenu(ctx context.Context, in *DeleteMenuRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := sysclient.NewScopeServiceClient(m.cli.Conn())
	return client.DeleteMenu(ctx, in, opts...)
}
