// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type AddOperateLogReq struct {
	Title             string `json:"title"`              //系统模块
	OperationType     string `json:"operation_type"`     //操作类型
	OperationName     string `json:"operation_name"`     //操作人员
	RequestMethod     string `json:"request_method"`     //请求方式
	OperationUrl      string `json:"operation_url"`      //操作方法
	OperationParams   string `json:"operation_params"`   //请求参数
	OperationResponse string `json:"operation_response"` //响应参数
	OperationStatus   int32  `json:"operation_status"`   //操作状态
	UseTime           int64  `json:"use_time"`
	Browser           string `json:"browser"`
	Os                string `json:"os"`
	OperationIp       string `json:"operation_ip"`
	OperationTime     string `json:"operation_time"`
}

type AddOperateLogResp struct {
	Pong string `json:"pong"`
}

type AddRolePermsRequest struct {
	RoleCode   string      `json:"role_code"` // 角色code
	RoleScopes []RoleScope `json:"role_scopes,optional"`
}

type AddScopeMenusRequest struct {
	ScopeId int64   `json:"scope_id"`
	MenuIds []int64 `json:"menu_ids"`
}

type AssignUserRoleRequest struct {
	UserId    int64    `json:"user_id"`
	RoleCodes []string `json:"role_codes"`
}

type BatchDeleteRolesRequest struct {
	RoleCodes  []string `json:"role_codes"`
	OperatorId int64    `json:"operator_id"`
}

type CreateMenuRequest struct {
	ParentId  int64  `json:"parent_id"`              // 父菜单ID
	MenuName  string `json:"menu_name"`              // 菜单名称
	MenuType  string `json:"menu_type"`              // 菜单类型 (M-目录, C-菜单, F-按钮)
	Path      string `json:"path,optional"`          // 路由路径
	Component string `json:"component"`              // 组件路径
	Redirect  string `json:"redirect,optional"`      // 重定向路径
	Icon      string `json:"icon,optional"`          // 菜单图标
	Sort      int32  `json:"sort,default=0"`         // 排序
	NoCache   bool   `json:"no_cache,default=false"` // 是否缓存
	Affix     bool   `json:"affix,default=false"`    // 是否固定在标签栏
	External  bool   `json:"external,default=false"` // 是否外部链接
	Hidden    bool   `json:"hidden,default=false"`   // 是否隐藏
	Status    int32  `json:"status,default=1"`       // 状态 (0-禁用, 1-正常)
	ScopeId   int64  `json:"scope_id"`               // 权限范围ID
	Remark    string `json:"remark,optional"`        // 备注
}

type CreateRoleRequest struct {
	RoleName    string `json:"role_name"`       // 角色名称
	RoleCode    string `json:"role_code"`       // 角色编码
	Description string `json:"description"`     // 角色描述
	Status      int32  `json:"status,optional"` // 状态 (0-禁用, 1-正常)
}

type CreateScopeRequest struct {
	ScopeName   string  `json:"scope_name"`        // 范围名称
	ScopeCode   string  `json:"scope_code"`        // 范围编码
	Description string  `json:"description"`       // 范围描述
	Sort        int32   `json:"sort,default=0"`    // 排序
	MenuIds     []int64 `json:"menu_ids,optional"` // 菜单ID
}

type CreateUserRequest struct {
	Username string  `json:"username"`           // 用户名
	Password string  `json:"password"`           // 密码
	Email    string  `json:"email,optional"`     // 邮箱
	Mobile   string  `json:"mobile,optional"`    // 手机号
	RealName string  `json:"real_name,optional"` // 真实姓名
	Gender   int32   `json:"gender,optional"`    // 性别 (0-未知, 1-男, 2-女)
	Status   int32   `json:"status,optional"`    // 状态 (0-禁用, 1-正常)
	RoleIds  []int64 `json:"role_ids,optional"`  // 角色ID列表
}

type DeleteMenuRequest struct {
	Id int64 `json:"id"` // 菜单ID
}

type DeleteOperateLogReq struct {
	Ids []int64 `json:"ids"`
}

type DeleteOperateLogResp struct {
	Pong string `json:"pong"`
}

type DeleteRolePermsRequest struct {
	RoleCode   string   `json:"role_code"` // 角色code
	ScopeCodes []string `json:"scope_codes"`
}

type DeleteRoleRequest struct {
	RoleCode string `json:"role_code"` // 角色ID
}

type DeleteScopeMenusRequest struct {
	ScopeId   int64   `json:"scope_id"`
	MenuIds   []int64 `json:"menu_ids,optional"`
	DeleteAll bool    `json:"delete_all,default=false"`
}

type DeleteScopeRequest struct {
	Id int64 `json:"id"` // 范围ID
}

type DeleteUserRequest struct {
	Id int64 `json:"id"` // 用户ID
}

type Empty struct {
}

type GetUserInfoRequest struct {
	UserId int64 `json:"user_id"`
}

type IdValue struct {
	Id int64 `path:"id"`
}

type LoginRequest struct {
	Username string `json:"username"` // 用户名
	Password string `json:"password"` // 密码
}

type LoginResponse struct {
	Id           int64  `json:"id"`            // 用户ID
	Username     string `json:"username"`      // 用户名
	AccessToken  string `json:"access_token"`  // JWT令牌
	RefreshToken string `json:"refresh_token"` // 刷新令牌
}

type Menu struct {
	Id        int64    `json:"id"`        // 菜单ID
	ParentId  int64    `json:"parent_id"` // 父菜单ID
	MenuType  string   `json:"menu_type"` // 菜单类型 (M-目录, C-菜单, F-按钮)
	Path      string   `json:"path"`      // 路由路径
	Component string   `json:"component"` // 组件路径
	Redirect  string   `json:"redirect"`  // 重定向路径
	Sort      int32    `json:"sort"`      // 排序
	External  bool     `json:"external"`  // 是否外部链接
	Hidden    bool     `json:"hidden"`    // 是否隐藏
	Status    int32    `json:"status"`    // 状态 (0-禁用, 1-正常)
	ScopeId   int64    `json:"scope_id"`  // 权限范围ID
	Remark    string   `json:"remark"`    // 备注
	Meta      MenuMeta `json:"meta"`      // 元数据
	Children  []Menu   `json:"children"`
	Perms     []string `json:"perms"`
}

type MenuListRequest struct {
	WithButton bool  `json:"with_button,optional"` // 是否包含按钮
	Status     int32 `json:"status"`               // 状态过滤
}

type MenuMeta struct {
	MenuName string `json:"menu_name"` // 菜单标题
	Icon     string `json:"icon"`      // 菜单图标
	NoCache  bool   `json:"no_cache"`  // 是否缓存
	Affix    bool   `json:"affix"`     // 是否固定在标签栏
}

type MenuTreeResponse struct {
	Menus []Menu `json:"menus"`
}

type OperateLog struct {
	Id                int64  `json:"id"`                 //编号
	Title             string `json:"title"`              //系统模块
	OperationType     string `json:"operation_type"`     //操作类型
	OperationName     string `json:"operation_name"`     //操作人员
	RequestMethod     string `json:"request_method"`     //请求方式
	OperationUrl      string `json:"operation_url"`      //操作方法
	OperationParams   string `json:"operation_params"`   //请求参数
	OperationResponse string `json:"operation_response"` //响应参数
	OperationStatus   int32  `json:"operation_status"`   //操作状态
	UseTime           int64  `json:"use_time"`           //执行时长(毫秒)
	Browser           string `json:"browser"`            //浏览器
	Os                string `json:"os"`                 //操作信息
	OperationIp       string `json:"operation_ip"`       //操作地址
	OperationTime     string `json:"operation_time"`     //操作时间
}

type OperateLogListData struct {
	PageResponse
	Data []OperateLog `json:"data"`
}

type PageRequest struct {
	Page     int64  `json:"page,default=1"`
	PageSize int64  `json:"page_size,default=10"`
	Keyword  string `json:"keyword,optional"`
}

type PageResponse struct {
	Total     int64 `json:"total"`
	Page      int64 `json:"page"`
	PageSize  int64 `json:"page_size"`
	TotalPage int64 `json:"total_page"`
}

type QueryOperateLogDetailReq struct {
	Id int64 `json:"id"`
}

type QueryOperateLogListReq struct {
	PageRequest
	OperationIp     string `json:"operation_ip,optional"`     //操作地址
	OperationName   string `json:"operation_name,optional"`   //操作人员
	OperationStatus int32  `json:"operation_status,optional"` //操作状态
	OperationType   string `json:"operation_type,optional"`   //操作类型
	OperationUrl    string `json:"operation_url,optional"`    //操作方法
	Title           string `json:"title,optional"`            //系统模块
	Os              string `json:"os,optional"`               //操作系统信息
	Browser         string `json:"browser,optional"`          //浏览器
	RequestMethod   string `json:"request_method,optional"`   //请求方式
}

type RefreshTokenRequest struct {
	Uid          int64  `json:"uid"`           // 用户ID
	RefreshToken string `json:"refresh_token"` // 刷新令牌
}

type RefreshTokenResponse struct {
	Token        string `json:"token"`         // 新的JWT令牌
	RefreshToken string `json:"refresh_token"` // 新的刷新令牌
}

type RegisterRequest struct {
	Username string `json:"username"`           // 用户名
	Password string `json:"password"`           // 密码
	Email    string `json:"email,optional"`     // 邮箱
	Mobile   string `json:"mobile,optional"`    // 手机号
	RealName string `json:"real_name,optional"` // 真实姓名
	Gender   int32  `json:"gender,optional"`    // 性别
	Avatar   string `json:"avatar,optional"`    // 头像
}

type RegisterResponse struct {
	Id           int64  `json:"id"`            // 用户ID
	Username     string `json:"username"`      // 用户名
	Token        string `json:"token"`         // JWT令牌
	RefreshToken string `json:"refresh_token"` // 刷新令牌
}

type Role struct {
	RoleId      int64  `json:"role_id"`     // 角色ID
	RoleName    string `json:"role_name"`   // 角色名称
	RoleCode    string `json:"role_code"`   // 角色编码
	Description string `json:"description"` // 角色描述
	Status      int32  `json:"status"`      // 状态（0-禁用，1-正常）
}

type RoleInfo struct {
	Role   Role            `json:"role"`
	Scopes []RoleScopeInfo `json:"scopes"`
}

type RoleListRequest struct {
	PageRequest PageRequest `json:"page_request"`
	Status      int32       `json:"status"` // 状态过滤
}

type RoleListResponse struct {
	PageResponse PageResponse `json:"page_response"`
	Roles        []Role       `json:"roles"`
}

type RoleScope struct {
	Id        int64    `json:"id"`
	RoleCode  string   `json:"role_code"`
	ScopeCode string   `json:"scope_code"`
	Perms     []string `json:"perms"`
}

type RoleScopeInfo struct {
	Scope
	Perms []string `json:"perms"`
}

type Scope struct {
	Id          int64  `json:"id"`          // 范围ID
	ScopeName   string `json:"scope_name"`  // 范围名称
	ScopeCode   string `json:"scope_code"`  // 范围编码
	Description string `json:"description"` // 范围描述
	Sort        int32  `json:"sort"`        // 排序
}

type ScopeInfo struct {
	Scope Scope  `json:"scope"`
	Menus []Menu `json:"menus"` // 菜单
}

type ScopeListRequest struct {
	PageRequest
}

type ScopeListResponse struct {
	PageResponse
	Scopes []Scope `json:"scopes"`
}

type StringValue struct {
	Value string `path:"value"`
}

type ToggleRoleStatusRequest struct {
	RoleCode string `json:"role_code"`
	Status   int32  `json:"status"` // 目标状态: 0=禁用, 1=启用
}

type ToggleUserStatusRequest struct {
	UserId int64 `json:"user_id"`
	Status int32 `json:"status"`
}

type UpdateMenuRequest struct {
	ID        int64  `json:"id"`
	ParentId  int64  `json:"parent_id,optional"` // 父菜单ID
	MenuName  string `json:"menu_name,optional"` // 菜单名称
	MenuType  string `json:"menu_type,optional"` // 菜单类型 (M-目录, C-菜单, F-按钮)
	Path      string `json:"path,optional"`      // 路由路径
	Component string `json:"component,optional"` // 组件路径
	Redirect  string `json:"redirect,optional"`  // 重定向路径
	Icon      string `json:"icon,optional"`      // 菜单图标
	Sort      int32  `json:"sort,optional"`      // 排序
	NoCache   bool   `json:"no_cache,optional"`  // 是否缓存
	Affix     bool   `json:"affix,optional"`     // 是否固定在标签栏
	External  bool   `json:"external,optional"`  // 是否外部链接
	Hidden    bool   `json:"hidden,optional"`    // 是否隐藏
	Status    int32  `json:"status,optional"`    // 状态 (0-禁用, 1-正常)
	Remark    string `json:"remark,optional"`    // 备注
}

type UpdatePasswordRequest struct {
	UserId   int64  `json:"user_id"`  // 用户ID
	Password string `json:"password"` // 新密码
}

type UpdateRolePermsRequest struct {
	RoleCode   string      `json:"role_code"` // 角色code
	RoleScopes []RoleScope `json:"role_scopes"`
}

type UpdateRoleRequest struct {
	RoleName    string `json:"role_name"`   // 角色名称
	RoleCode    string `json:"role_code"`   // 角色编码
	Description string `json:"description"` // 角色描述
	Status      int32  `json:"status"`      // 状态 (0-禁用, 1-正常)
}

type UpdateScopeRequest struct {
	Id          int64  `json:"id"`                   // 范围ID
	ScopeName   string `json:"scope_name,optional"`  // 范围名称
	ScopeCode   string `json:"scope_code"`           // 范围编码
	Description string `json:"description,optional"` // 范围描述
	Sort        int32  `json:"sort,optional"`        // 排序
}

type UpdateUserPasswordRequest struct {
	OldPassword string `json:"old_password"` // 旧密码
	NewPassword string `json:"new_password"` // 新密码
}

type UpdateUserRequest struct {
	Id       int64  `json:"id"`                 // 用户ID
	Email    string `json:"email,optional"`     // 邮箱
	Mobile   string `json:"mobile,optional"`    // 手机号
	RealName string `json:"real_name,optional"` // 真实姓名
	Gender   int32  `json:"gender,optional"`    // 性别 (0-未知, 1-男, 2-女)
	Avatar   string `json:"avatar,optional"`    // 头像URL
}

type User struct {
	Id       int64  `json:"id"`        // 用户ID
	Username string `json:"username"`  // 用户名
	Email    string `json:"email"`     // 邮箱
	Mobile   string `json:"mobile"`    // 手机号
	RealName string `json:"real_name"` // 真实姓名
	Gender   int32  `json:"gender"`    // 性别 (0-未知, 1-男, 2-女)
	Status   int32  `json:"status"`    // 状态 (0-禁用, 1-正常)
	Avatar   string `json:"avatar"`    // 头像
}

type UserInfo struct {
	User
	Roles    []Role `json:"roles"`     // 角色列表
	MenuTree []Menu `json:"menu_tree"` // 菜单列表
}

type UserListRequest struct {
	PageRequest
	Status int32 `json:"status"` // 状态过滤
}

type UserListResponse struct {
	PageResponse
	Users []User `json:"users"`
}
