-- 用户表
CREATE TABLE `blog_user` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted_at` DATETIME DEFAULT NULL COMMENT '删除时间',
  `username` VARCHAR(255) NOT NULL COMMENT '用户名',
  `nickname` VARCHAR(255) DEFAULT NULL COMMENT '昵称',
  `password` VARCHAR(255) NOT NULL COMMENT '密码',
  `salt` VARCHAR(255) DEFAULT NULL COMMENT '盐值',
  `avatar` VARCHAR(255) DEFAULT NULL COMMENT '头像',
  `gender` TINYINT DEFAULT 0 COMMENT '性别 0-未知 1-男 2-女',
  `introduction` TEXT DEFAULT NULL COMMENT '个人介绍',
  `birthday` VARCHAR(50) DEFAULT NULL COMMENT '出生日期',
  `mobile` VARCHAR(20) DEFAULT NULL COMMENT '手机号',
  `email` VARCHAR(100) DEFAULT NULL COMMENT '邮箱',
  `status` TINYINT DEFAULT 0 COMMENT '状态 0-正常 1-禁用',
  `login_time` DATETIME DEFAULT NULL COMMENT '最近登录时间',
  `last_login_ip` VARCHAR(50) DEFAULT NULL COMMENT '最近登录IP',
  `login_count` INT DEFAULT 0 COMMENT '登录次数',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_username` (`username`),
  KEY `idx_email` (`email`),
  KEY `idx_mobile` (`mobile`),
  KEY `idx_deleted_at` (`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='用户表';