// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: sys.proto

package roleservice

import (
	"context"

	"zero-admin/rpc/sys/sysclient"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddOperateLogReq          = sysclient.AddOperateLogReq
	AddOperateLogResp         = sysclient.AddOperateLogResp
	AddRolePermsRequest       = sysclient.AddRolePermsRequest
	AddScopeMenusRequest      = sysclient.AddScopeMenusRequest
	AssignUserRoleRequest     = sysclient.AssignUserRoleRequest
	BatchDeleteRolesRequest   = sysclient.BatchDeleteRolesRequest
	CreateMenuRequest         = sysclient.CreateMenuRequest
	CreateRoleRequest         = sysclient.CreateRoleRequest
	CreateScopeRequest        = sysclient.CreateScopeRequest
	CreateUserRequest         = sysclient.CreateUserRequest
	DeleteMenuRequest         = sysclient.DeleteMenuRequest
	DeleteOperateLogReq       = sysclient.DeleteOperateLogReq
	DeleteOperateLogResp      = sysclient.DeleteOperateLogResp
	DeleteRolePermsRequest    = sysclient.DeleteRolePermsRequest
	DeleteRoleRequest         = sysclient.DeleteRoleRequest
	DeleteScopeMenusRequest   = sysclient.DeleteScopeMenusRequest
	DeleteScopeRequest        = sysclient.DeleteScopeRequest
	DeleteUserRequest         = sysclient.DeleteUserRequest
	Empty                     = sysclient.Empty
	GetUserInfoRequest        = sysclient.GetUserInfoRequest
	Int64Value                = sysclient.Int64Value
	LoginRequest              = sysclient.LoginRequest
	LoginResponse             = sysclient.LoginResponse
	Menu                      = sysclient.Menu
	MenuListRequest           = sysclient.MenuListRequest
	MenuTreeResponse          = sysclient.MenuTreeResponse
	OperateLog                = sysclient.OperateLog
	OperateLogListData        = sysclient.OperateLogListData
	PageRequest               = sysclient.PageRequest
	PageResponse              = sysclient.PageResponse
	QueryOperateLogDetailReq  = sysclient.QueryOperateLogDetailReq
	QueryOperateLogListReq    = sysclient.QueryOperateLogListReq
	RefreshTokenRequest       = sysclient.RefreshTokenRequest
	RefreshTokenResponse      = sysclient.RefreshTokenResponse
	Role                      = sysclient.Role
	RoleInfo                  = sysclient.RoleInfo
	RoleListRequest           = sysclient.RoleListRequest
	RoleListResponse          = sysclient.RoleListResponse
	RoleScope                 = sysclient.RoleScope
	RoleScopeInfo             = sysclient.RoleScopeInfo
	Scope                     = sysclient.Scope
	ScopeInfo                 = sysclient.ScopeInfo
	ScopeListRequest          = sysclient.ScopeListRequest
	ScopeListResponse         = sysclient.ScopeListResponse
	ToggleRoleStatusRequest   = sysclient.ToggleRoleStatusRequest
	ToggleUserStatusRequest   = sysclient.ToggleUserStatusRequest
	UpdateMenuRequest         = sysclient.UpdateMenuRequest
	UpdateRolePermsRequest    = sysclient.UpdateRolePermsRequest
	UpdateRoleRequest         = sysclient.UpdateRoleRequest
	UpdateScopeRequest        = sysclient.UpdateScopeRequest
	UpdateUserPasswordRequest = sysclient.UpdateUserPasswordRequest
	UpdateUserRequest         = sysclient.UpdateUserRequest
	User                      = sysclient.User
	UserInfo                  = sysclient.UserInfo
	UserListRequest           = sysclient.UserListRequest
	UserListResponse          = sysclient.UserListResponse

	RoleService interface {
		// 角色列表
		GetRoleList(ctx context.Context, in *RoleListRequest, opts ...grpc.CallOption) (*RoleListResponse, error)
		// 创建角色
		CreateRole(ctx context.Context, in *CreateRoleRequest, opts ...grpc.CallOption) (*Role, error)
		// 更新角色
		UpdateRole(ctx context.Context, in *UpdateRoleRequest, opts ...grpc.CallOption) (*Role, error)
		// 禁用角色
		ToggleRoleStatus(ctx context.Context, in *ToggleRoleStatusRequest, opts ...grpc.CallOption) (*Role, error)
		// 删除角色
		DeleteRole(ctx context.Context, in *DeleteRoleRequest, opts ...grpc.CallOption) (*Empty, error)
		BatchDeleteRoles(ctx context.Context, in *BatchDeleteRolesRequest, opts ...grpc.CallOption) (*Empty, error)
		// 添加角色权限
		AddRolePerms(ctx context.Context, in *AddRolePermsRequest, opts ...grpc.CallOption) (*RoleInfo, error)
		// 更新角色权限
		UpdateRolePerms(ctx context.Context, in *UpdateRolePermsRequest, opts ...grpc.CallOption) (*RoleInfo, error)
		// 删除角色权限
		DeleteRolePerms(ctx context.Context, in *DeleteRolePermsRequest, opts ...grpc.CallOption) (*RoleInfo, error)
		// 获取角色权限
		GetRolePerms(ctx context.Context, in *Int64Value, opts ...grpc.CallOption) (*RoleInfo, error)
	}

	defaultRoleService struct {
		cli zrpc.Client
	}
)

func NewRoleService(cli zrpc.Client) RoleService {
	return &defaultRoleService{
		cli: cli,
	}
}

// 角色列表
func (m *defaultRoleService) GetRoleList(ctx context.Context, in *RoleListRequest, opts ...grpc.CallOption) (*RoleListResponse, error) {
	client := sysclient.NewRoleServiceClient(m.cli.Conn())
	return client.GetRoleList(ctx, in, opts...)
}

// 创建角色
func (m *defaultRoleService) CreateRole(ctx context.Context, in *CreateRoleRequest, opts ...grpc.CallOption) (*Role, error) {
	client := sysclient.NewRoleServiceClient(m.cli.Conn())
	return client.CreateRole(ctx, in, opts...)
}

// 更新角色
func (m *defaultRoleService) UpdateRole(ctx context.Context, in *UpdateRoleRequest, opts ...grpc.CallOption) (*Role, error) {
	client := sysclient.NewRoleServiceClient(m.cli.Conn())
	return client.UpdateRole(ctx, in, opts...)
}

// 禁用角色
func (m *defaultRoleService) ToggleRoleStatus(ctx context.Context, in *ToggleRoleStatusRequest, opts ...grpc.CallOption) (*Role, error) {
	client := sysclient.NewRoleServiceClient(m.cli.Conn())
	return client.ToggleRoleStatus(ctx, in, opts...)
}

// 删除角色
func (m *defaultRoleService) DeleteRole(ctx context.Context, in *DeleteRoleRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := sysclient.NewRoleServiceClient(m.cli.Conn())
	return client.DeleteRole(ctx, in, opts...)
}

func (m *defaultRoleService) BatchDeleteRoles(ctx context.Context, in *BatchDeleteRolesRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := sysclient.NewRoleServiceClient(m.cli.Conn())
	return client.BatchDeleteRoles(ctx, in, opts...)
}

// 添加角色权限
func (m *defaultRoleService) AddRolePerms(ctx context.Context, in *AddRolePermsRequest, opts ...grpc.CallOption) (*RoleInfo, error) {
	client := sysclient.NewRoleServiceClient(m.cli.Conn())
	return client.AddRolePerms(ctx, in, opts...)
}

// 更新角色权限
func (m *defaultRoleService) UpdateRolePerms(ctx context.Context, in *UpdateRolePermsRequest, opts ...grpc.CallOption) (*RoleInfo, error) {
	client := sysclient.NewRoleServiceClient(m.cli.Conn())
	return client.UpdateRolePerms(ctx, in, opts...)
}

// 删除角色权限
func (m *defaultRoleService) DeleteRolePerms(ctx context.Context, in *DeleteRolePermsRequest, opts ...grpc.CallOption) (*RoleInfo, error) {
	client := sysclient.NewRoleServiceClient(m.cli.Conn())
	return client.DeleteRolePerms(ctx, in, opts...)
}

// 获取角色权限
func (m *defaultRoleService) GetRolePerms(ctx context.Context, in *Int64Value, opts ...grpc.CallOption) (*RoleInfo, error) {
	client := sysclient.NewRoleServiceClient(m.cli.Conn())
	return client.GetRolePerms(ctx, in, opts...)
}
