// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	sysauth "zero-admin/api/admin/internal/handler/sys/auth"
	sysoperatelog "zero-admin/api/admin/internal/handler/sys/operatelog"
	sysrole "zero-admin/api/admin/internal/handler/sys/role"
	sysscope "zero-admin/api/admin/internal/handler/sys/scope"
	sysuser "zero-admin/api/admin/internal/handler/sys/user"
	"zero-admin/api/admin/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: sysauth.LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: sysauth.RegisterHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/sys/auth"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/logout",
				Handler: sysauth.LogoutHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/refresh_token",
				Handler: sysauth.RefreshTokenHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/sys/auth"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.VerifyPermission},
			[]rest.Route{
				{
					Method:  http.MethodDelete,
					Path:    "/operate-log",
					Handler: sysoperatelog.DeleteOperateLogHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/operate-log/:id",
					Handler: sysoperatelog.QueryOperateLogDetailHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/operate-log/list",
					Handler: sysoperatelog.QueryOperateLogListHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/sys/operatelog"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.VerifyPermission},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/role",
					Handler: sysrole.CreateRoleHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/role",
					Handler: sysrole.UpdateRoleHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/role",
					Handler: sysrole.DeleteRoleHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/role/batch-delete",
					Handler: sysrole.BatchDeleteRolesHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/role/list",
					Handler: sysrole.GetRoleListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/role/perms",
					Handler: sysrole.AddRolePermsHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/role/perms",
					Handler: sysrole.UpdateRolePermsHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/role/perms",
					Handler: sysrole.DeleteRolePermsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/role/perms/:value",
					Handler: sysrole.GetRolePermsHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/role/status",
					Handler: sysrole.ToggleRoleStatusHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/sys/role"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.VerifyPermission},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/menu",
					Handler: sysscope.CreateMenuHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/menu",
					Handler: sysscope.UpdateMenuHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/menu",
					Handler: sysscope.DeleteMenuHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/menu/:id",
					Handler: sysscope.GetMenuByIdHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/menu/tree",
					Handler: sysscope.GetMenuTreeHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/scope",
					Handler: sysscope.CreateScopeHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/scope",
					Handler: sysscope.UpdateScopeHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/scope",
					Handler: sysscope.DeleteScopeHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/scope/:id",
					Handler: sysscope.GetScopeByIdHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/scope/list",
					Handler: sysscope.GetScopeListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/scope/menus",
					Handler: sysscope.AddScopeMenusHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/scope/menus",
					Handler: sysscope.DeleteScopeMenusHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/scope/menus/:id",
					Handler: sysscope.GetScopeMenusHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/sys/scope"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.VerifyPermission},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/user",
					Handler: sysuser.CreateUserHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/user",
					Handler: sysuser.UpdateUserHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/user",
					Handler: sysuser.DeleteUserHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/user/:id",
					Handler: sysuser.GetUserByIdHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/user/assign-role",
					Handler: sysuser.AssignUserRoleHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/user/info",
					Handler: sysuser.GetUserInfoHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/user/list",
					Handler: sysuser.GetUserListHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/user/password",
					Handler: sysuser.UpdateUserPasswordHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/user/status",
					Handler: sysuser.ToggleUserStatusHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/sys/user"),
	)
}
