// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: sys.proto

package server

import (
	"context"

	"zero-admin/rpc/sys/internal/logic/permissionservice"
	"zero-admin/rpc/sys/internal/svc"
	"zero-admin/rpc/sys/sysclient"
)

type PermissionServiceServer struct {
	svcCtx *svc.ServiceContext
	sysclient.UnimplementedPermissionServiceServer
}

func NewPermissionServiceServer(svcCtx *svc.ServiceContext) *PermissionServiceServer {
	return &PermissionServiceServer{
		svcCtx: svcCtx,
	}
}

// 用户管理
func (s *PermissionServiceServer) GetUserList(ctx context.Context, in *sysclient.UserListRequest) (*sysclient.UserListResponse, error) {
	l := permissionservicelogic.NewGetUserListLogic(ctx, s.svcCtx)
	return l.GetUserList(in)
}

func (s *PermissionServiceServer) GetUserById(ctx context.Context, in *sysclient.Int64Value) (*sysclient.UserInfo, error) {
	l := permissionservicelogic.NewGetUserByIdLogic(ctx, s.svcCtx)
	return l.GetUserById(in)
}

func (s *PermissionServiceServer) CreateUser(ctx context.Context, in *sysclient.CreateUserRequest) (*sysclient.UserInfo, error) {
	l := permissionservicelogic.NewCreateUserLogic(ctx, s.svcCtx)
	return l.CreateUser(in)
}

func (s *PermissionServiceServer) UpdateUser(ctx context.Context, in *sysclient.UpdateUserRequest) (*sysclient.UserInfo, error) {
	l := permissionservicelogic.NewUpdateUserLogic(ctx, s.svcCtx)
	return l.UpdateUser(in)
}

func (s *PermissionServiceServer) DeleteUser(ctx context.Context, in *sysclient.DeleteUserRequest) (*sysclient.Empty, error) {
	l := permissionservicelogic.NewDeleteUserLogic(ctx, s.svcCtx)
	return l.DeleteUser(in)
}

func (s *PermissionServiceServer) UpdateUserPassword(ctx context.Context, in *sysclient.UpdateUserPasswordRequest) (*sysclient.Empty, error) {
	l := permissionservicelogic.NewUpdateUserPasswordLogic(ctx, s.svcCtx)
	return l.UpdateUserPassword(in)
}

// 角色管理
func (s *PermissionServiceServer) GetRoleList(ctx context.Context, in *sysclient.RoleListRequest) (*sysclient.RoleListResponse, error) {
	l := permissionservicelogic.NewGetRoleListLogic(ctx, s.svcCtx)
	return l.GetRoleList(in)
}

func (s *PermissionServiceServer) GetRoleById(ctx context.Context, in *sysclient.Int64Value) (*sysclient.RoleInfo, error) {
	l := permissionservicelogic.NewGetRoleByIdLogic(ctx, s.svcCtx)
	return l.GetRoleById(in)
}

func (s *PermissionServiceServer) CreateRole(ctx context.Context, in *sysclient.CreateRoleRequest) (*sysclient.RoleInfo, error) {
	l := permissionservicelogic.NewCreateRoleLogic(ctx, s.svcCtx)
	return l.CreateRole(in)
}

func (s *PermissionServiceServer) UpdateRole(ctx context.Context, in *sysclient.UpdateRoleRequest) (*sysclient.RoleInfo, error) {
	l := permissionservicelogic.NewUpdateRoleLogic(ctx, s.svcCtx)
	return l.UpdateRole(in)
}

func (s *PermissionServiceServer) DeleteRole(ctx context.Context, in *sysclient.DeleteRoleRequest) (*sysclient.Empty, error) {
	l := permissionservicelogic.NewDeleteRoleLogic(ctx, s.svcCtx)
	return l.DeleteRole(in)
}

// 菜单管理
func (s *PermissionServiceServer) GetMenuTree(ctx context.Context, in *sysclient.MenuListRequest) (*sysclient.MenuTreeResponse, error) {
	l := permissionservicelogic.NewGetMenuTreeLogic(ctx, s.svcCtx)
	return l.GetMenuTree(in)
}

func (s *PermissionServiceServer) GetMenuById(ctx context.Context, in *sysclient.Int64Value) (*sysclient.Menu, error) {
	l := permissionservicelogic.NewGetMenuByIdLogic(ctx, s.svcCtx)
	return l.GetMenuById(in)
}

func (s *PermissionServiceServer) CreateMenu(ctx context.Context, in *sysclient.CreateMenuRequest) (*sysclient.Menu, error) {
	l := permissionservicelogic.NewCreateMenuLogic(ctx, s.svcCtx)
	return l.CreateMenu(in)
}

func (s *PermissionServiceServer) UpdateMenu(ctx context.Context, in *sysclient.UpdateMenuRequest) (*sysclient.Menu, error) {
	l := permissionservicelogic.NewUpdateMenuLogic(ctx, s.svcCtx)
	return l.UpdateMenu(in)
}

func (s *PermissionServiceServer) DeleteMenu(ctx context.Context, in *sysclient.DeleteMenuRequest) (*sysclient.Empty, error) {
	l := permissionservicelogic.NewDeleteMenuLogic(ctx, s.svcCtx)
	return l.DeleteMenu(in)
}

// 安全范围管理
func (s *PermissionServiceServer) GetScopeList(ctx context.Context, in *sysclient.ScopeListRequest) (*sysclient.ScopeListResponse, error) {
	l := permissionservicelogic.NewGetScopeListLogic(ctx, s.svcCtx)
	return l.GetScopeList(in)
}

func (s *PermissionServiceServer) GetScopeById(ctx context.Context, in *sysclient.Int64Value) (*sysclient.ScopeInfo, error) {
	l := permissionservicelogic.NewGetScopeByIdLogic(ctx, s.svcCtx)
	return l.GetScopeById(in)
}

func (s *PermissionServiceServer) CreateScope(ctx context.Context, in *sysclient.CreateScopeRequest) (*sysclient.ScopeInfo, error) {
	l := permissionservicelogic.NewCreateScopeLogic(ctx, s.svcCtx)
	return l.CreateScope(in)
}

func (s *PermissionServiceServer) UpdateScope(ctx context.Context, in *sysclient.UpdateScopeRequest) (*sysclient.ScopeInfo, error) {
	l := permissionservicelogic.NewUpdateScopeLogic(ctx, s.svcCtx)
	return l.UpdateScope(in)
}

func (s *PermissionServiceServer) DeleteScope(ctx context.Context, in *sysclient.DeleteScopeRequest) (*sysclient.Empty, error) {
	l := permissionservicelogic.NewDeleteScopeLogic(ctx, s.svcCtx)
	return l.DeleteScope(in)
}
