// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: sys.proto

package userservice

import (
	"context"

	"zero-admin/rpc/sys/sysclient"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateMenuRequest         = sysclient.CreateMenuRequest
	CreateRoleRequest         = sysclient.CreateRoleRequest
	CreateScopeRequest        = sysclient.CreateScopeRequest
	CreateUserRequest         = sysclient.CreateUserRequest
	DeleteMenuRequest         = sysclient.DeleteMenuRequest
	DeleteRoleRequest         = sysclient.DeleteRoleRequest
	DeleteScopeRequest        = sysclient.DeleteScopeRequest
	DeleteUserRequest         = sysclient.DeleteUserRequest
	Empty                     = sysclient.Empty
	GetUserInfoRequest        = sysclient.GetUserInfoRequest
	Int64Value                = sysclient.Int64Value
	LoginRequest              = sysclient.LoginRequest
	LoginResponse             = sysclient.LoginResponse
	Menu                      = sysclient.Menu
	MenuListRequest           = sysclient.MenuListRequest
	MenuTreeResponse          = sysclient.MenuTreeResponse
	PageRequest               = sysclient.PageRequest
	PageResponse              = sysclient.PageResponse
	RefreshTokenRequest       = sysclient.RefreshTokenRequest
	RefreshTokenResponse      = sysclient.RefreshTokenResponse
	Role                      = sysclient.Role
	RoleInfo                  = sysclient.RoleInfo
	RoleListRequest           = sysclient.RoleListRequest
	RoleListResponse          = sysclient.RoleListResponse
	Scope                     = sysclient.Scope
	ScopeInfo                 = sysclient.ScopeInfo
	ScopeListRequest          = sysclient.ScopeListRequest
	ScopeListResponse         = sysclient.ScopeListResponse
	UpdateMenuRequest         = sysclient.UpdateMenuRequest
	UpdateRoleRequest         = sysclient.UpdateRoleRequest
	UpdateScopeRequest        = sysclient.UpdateScopeRequest
	UpdateUserPasswordRequest = sysclient.UpdateUserPasswordRequest
	UpdateUserRequest         = sysclient.UpdateUserRequest
	User                      = sysclient.User
	UserInfo                  = sysclient.UserInfo
	UserListRequest           = sysclient.UserListRequest
	UserListResponse          = sysclient.UserListResponse

	UserService interface {
		// 用户管理
		GetUserList(ctx context.Context, in *UserListRequest, opts ...grpc.CallOption) (*UserListResponse, error)
		GetUserById(ctx context.Context, in *Int64Value, opts ...grpc.CallOption) (*UserInfo, error)
		CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*UserInfo, error)
		UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UserInfo, error)
		DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*Empty, error)
		UpdateUserPassword(ctx context.Context, in *UpdateUserPasswordRequest, opts ...grpc.CallOption) (*Empty, error)
		// 获取当前用户信息
		GetUserInfo(ctx context.Context, in *GetUserInfoRequest, opts ...grpc.CallOption) (*UserInfo, error)
	}

	defaultUserService struct {
		cli zrpc.Client
	}
)

func NewUserService(cli zrpc.Client) UserService {
	return &defaultUserService{
		cli: cli,
	}
}

// 用户管理
func (m *defaultUserService) GetUserList(ctx context.Context, in *UserListRequest, opts ...grpc.CallOption) (*UserListResponse, error) {
	client := sysclient.NewUserServiceClient(m.cli.Conn())
	return client.GetUserList(ctx, in, opts...)
}

func (m *defaultUserService) GetUserById(ctx context.Context, in *Int64Value, opts ...grpc.CallOption) (*UserInfo, error) {
	client := sysclient.NewUserServiceClient(m.cli.Conn())
	return client.GetUserById(ctx, in, opts...)
}

func (m *defaultUserService) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*UserInfo, error) {
	client := sysclient.NewUserServiceClient(m.cli.Conn())
	return client.CreateUser(ctx, in, opts...)
}

func (m *defaultUserService) UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UserInfo, error) {
	client := sysclient.NewUserServiceClient(m.cli.Conn())
	return client.UpdateUser(ctx, in, opts...)
}

func (m *defaultUserService) DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := sysclient.NewUserServiceClient(m.cli.Conn())
	return client.DeleteUser(ctx, in, opts...)
}

func (m *defaultUserService) UpdateUserPassword(ctx context.Context, in *UpdateUserPasswordRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := sysclient.NewUserServiceClient(m.cli.Conn())
	return client.UpdateUserPassword(ctx, in, opts...)
}

// 获取当前用户信息
func (m *defaultUserService) GetUserInfo(ctx context.Context, in *GetUserInfoRequest, opts ...grpc.CallOption) (*UserInfo, error) {
	client := sysclient.NewUserServiceClient(m.cli.Conn())
	return client.GetUserInfo(ctx, in, opts...)
}
