// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	article "zero-admin/api/blog/internal/handler/article"
	articleCategory "zero-admin/api/blog/internal/handler/articleCategory"
	articleComments "zero-admin/api/blog/internal/handler/articleComments"
	home "zero-admin/api/blog/internal/handler/home"
	user "zero-admin/api/blog/internal/handler/user"
	welcome "zero-admin/api/blog/internal/handler/welcome"
	"zero-admin/api/blog/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JwtExpireAuth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/",
					Handler: article.CreateArticleHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/",
					Handler: article.UpdateArticleHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/",
					Handler: article.DeleteArticleHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:id",
					Handler: article.GetArticleHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/category/articles",
					Handler: article.ListArticleByCategoryHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/tags",
					Handler: article.ListArticleTagsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/tags/article",
					Handler: article.ListArticleByTagsHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/blog/article"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JwtExpireAuth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/",
					Handler: articleCategory.ListArticleCategoryHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/",
					Handler: articleCategory.CreateArticleCategoryHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/",
					Handler: articleCategory.UpdateArticleCategoryHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/",
					Handler: articleCategory.DeleteArticleCategoryHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:id/articles",
					Handler: articleCategory.GetArticleCategoryHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/categories/all",
					Handler: articleCategory.GetAllArticleCategoriesHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/blog/article/category"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JwtExpireAuth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/",
					Handler: articleComments.GetArticleCommentsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/",
					Handler: articleComments.CreateArticleCommentHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/",
					Handler: articleComments.DeleteArticleCommentHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/reply",
					Handler: articleComments.GetReplyCommentsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/unread",
					Handler: articleComments.GetUnreadCommentsHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/blog/article/comments"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/articles",
				Handler: home.ListHomeArticleHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/notice",
				Handler: home.GetNoticeHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/recommend",
				Handler: home.ListRecommendArticleHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/search",
				Handler: home.SearchHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/search/hot",
				Handler: home.GetHotSearchHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/search/suggest",
				Handler: home.SearchSuggestHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/blog/home"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JwtExpireAuth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/stats",
					Handler: home.GetArticleStatsHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/blog/home"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JwtExpireAuth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/",
					Handler: user.GetUserInfoHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/",
					Handler: user.UpdateUserInfoHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/article/timeline",
					Handler: user.GetUserArticleTimelineHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/changepassword",
					Handler: user.ChangePasswordHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/blog/user"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/captcha",
				Handler: welcome.GetCaptchaHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: welcome.LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: welcome.RegisterHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/blog/welcome"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JwtExpireAuth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/deregistration",
					Handler: welcome.DeregistrationHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/logoff",
					Handler: welcome.LogoffHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/blog/welcome"),
	)
}
