// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: sys.proto

package server

import (
	"context"

	"zero-admin/rpc/sys/internal/logic/authservice"
	"zero-admin/rpc/sys/internal/svc"
	"zero-admin/rpc/sys/sysclient"
)

type AuthServiceServer struct {
	svcCtx *svc.ServiceContext
	sysclient.UnimplementedAuthServiceServer
}

func NewAuthServiceServer(svcCtx *svc.ServiceContext) *AuthServiceServer {
	return &AuthServiceServer{
		svcCtx: svcCtx,
	}
}

// 用户登录
func (s *AuthServiceServer) Login(ctx context.Context, in *sysclient.LoginRequest) (*sysclient.LoginResponse, error) {
	l := authservicelogic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

// 刷新令牌
func (s *AuthServiceServer) RefreshToken(ctx context.Context, in *sysclient.RefreshTokenRequest) (*sysclient.RefreshTokenResponse, error) {
	l := authservicelogic.NewRefreshTokenLogic(ctx, s.svcCtx)
	return l.RefreshToken(in)
}

// 获取当前用户信息
func (s *AuthServiceServer) GetCurrentUser(ctx context.Context, in *sysclient.GetCurrentUserRequest) (*sysclient.UserInfo, error) {
	l := authservicelogic.NewGetCurrentUserLogic(ctx, s.svcCtx)
	return l.GetCurrentUser(in)
}
