// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type Article struct {
	Id          int64    `json:"id"`
	AuthorId    int64    `json:"authorId"`
	AuthorName  string   `json:"authorName"`
	Title       string   `json:"title"`
	Summary     string   `json:"summary"`
	Content     string   `json:"content,omitempty"`
	Views       int64    `json:"views"`
	Likes       int64    `json:"likes"`
	Comments    int64    `json:"comments"`
	Tags        []string `json:"tags"`
	Cover       string   `json:"cover"`
	CreatedTime int64    `json:"createdTime"`
	UpdatedTime int64    `json:"updatedTime"`
}

type ArticleCategory struct {
	Id           int64     `json:"id" gorm:"column:id"` // 分类ID
	Name         string    `json:"name" gorm:"name"`    // 分类名称
	Description  string    `json:"description,optional" gorm:"description"`
	Articles     []Article `json:"articles,omitempty" gorm:"-"`      // 文章
	ArticleCount int64     `json:"article_count,omitempty" gorm:"-"` // 文章数量
}

type ArticleStats struct {
	ArticleNum  int64 `json:"articleNum"`
	CategoryNum int64 `json:"categoryNum"`
	CommentNum  int64 `json:"commentNum"`
}

type CaptchaResp struct {
	CaptchaId    string `json:"captcha_id"`    // 验证码ID
	CaptchaImage string `json:"captcha_image"` // 验证码图片
}

type ChangePasswordReq struct {
	OldPassword string `json:"oldPassword"`
	NewPassword string `json:"newPassword"`
}

type Comment struct {
	Id         int64    `json:"id"`
	UserId     int64    `json:"userId"`
	UserName   string   `json:"userName"`
	UserAvatar string   `json:"userAvatar"`
	Content    string   `json:"content"`
	Images     []string `json:"images"`
	Replies    []Reply  `json:"replies"`
	ReplyCount int64    `json:"replyCount"`
	CreatedAt  int64    `json:"createdAt"`
	Read       int      `json:"read"`
}

type CreateArticleCategoryReq struct {
	Name        string `json:"name"`
	Description string `json:"description,optional"`
}

type CreateArticleCategoryResp struct {
	Id int64 `json:"id"`
}

type CreateArticleCommentReq struct {
	ArticleId       int64    `json:"articleId"`                // 文章id
	ParentCommentId int64    `json:"parentCommentId,optional"` // 回复评论的父评论id
	ReplyCommentId  int64    `json:"replyCommentId,optional"`  // 回复评论id
	UserId          int64    `json:"userId"`
	ReplyTo         int64    `json:"replyTo"`
	Content         string   `json:"content"`
	Imgs            []string `json:"imgs"`
}

type CreateArticleCommentResp struct {
	Id int64 `json:"id"`
}

type CreateArticleReq struct {
	Title      string   `json:"title"`
	Summary    string   `json:"summary"`
	Content    string   `json:"content"`
	Tags       []string `json:"tags"`
	CategoryId int64    `json:"categoryId"`
	Cover      string   `json:"cover,optional"`
}

type CreateArticleResp struct {
	Id int64 `json:"id"`
}

type DeleteArticleCategoryReq struct {
	Id int64 `json:"id"`
}

type DeleteArticleCommentReq struct {
	ArticleId int64 `json:"articleId"`
	CommentId int64 `json:"commentId"`
}

type DeleteArticleReq struct {
	Id int64 `json:"id"`
}

type Empty struct {
}

type GetArtcileCommentsResp struct {
	PageResponse
	Comments []Comment `json:"comments"`
}

type GetArticleCommentsReq struct {
	PageRequest
	ArticleId       int64  `form:"articleId"`
	Tab             string `form:"tab,options=latest|hot"`
	TargetCommentId int64  `form:"targetCommentId,optional"` // 回复评论，跳转时传参
}

type GetReplyCommentsReq struct {
	PageRequest
	ArticleId int64 `form:"articleId"`
	CommentId int64 `form:"commentId"`
}

type GetReplyCommentsResp struct {
	PageResponse
	Replies []Reply `json:"replies"`
}

type GetUnreadCommentsReq struct {
	PageRequest
}

type GetUnreadCommentsResp struct {
	PageResponse
	Replies []Reply `json:"replies"`
}

type HomeArticleReq struct {
	PageRequest
	Tab string `form:"tab,options=recent|vote|hot"`
}

type HomeArticleResp struct {
	PageResponse
	Articles []Article `json:"articles"`
}

type IdValue struct {
	Id int64 `path:"id"`
}

type ListArticleByCategoryReq struct {
	PageRequest
	CategoryId int64 `json:"category_id"`
}

type ListArticleByCategoryResp struct {
	PageResponse
	Articles []Article `json:"articles"`
}

type ListArticleByTagsReq struct {
	PageRequest
	Tag string `json:"tag"`
}

type ListArticleByTagsResp struct {
	PageResponse
	Articles []Article `json:"articles"`
}

type ListArticleCategoryReq struct {
	PageRequest
}

type ListArticleCategoryResp struct {
	PageResponse
	Categories []ArticleCategory `json:"categories"`
}

type ListArticleTagsReq struct {
	PageRequest
}

type ListArticleTagsResp struct {
	PageResponse
	Articles []Article `json:"articles"`
}

type LoginReq struct {
	Username  string `json:"username"`  // 用户名
	Password  string `json:"password"`  // 密码
	CaptchaId string `json:"captchaId"` // 验证码ID
	Captcha   string `json:"captcha"`   // 验证码
}

type LoginResp struct {
	UserId       int64  `json:"userId"`       // 用户ID
	AccessToken  string `json:"accessToken"`  // JWT令牌
	RefreshToken string `json:"refreshToken"` // 刷新令牌
}

type Notice struct {
	Id        int64  `json:"id"`
	Content   string `json:"content"`
	CreatedAt int64  `json:"createdAt"`
	UpdatedAt int64  `json:"updatedAt"`
}

type PageRequest struct {
	Page      int64  `form:"page,default=1""`
	PageSize  int64  `form:"pageSize,default=10"`
	Keyword   string `form:"keyword,optional"`
	FullQuery bool   `form:"fullQuery,default=false"`
}

type PageResponse struct {
	Total     int64 `json:"total"`
	Page      int64 `json:"page"`
	PageSize  int64 `json:"pageSize"`
	TotalPage int64 `json:"totalPage"`
}

type RegisterReq struct {
	Username     string `json:"username"` // 用户名
	Password     string `json:"password"` // 密码
	Nickname     string `json:"nickname,optional"`
	Email        string `json:"email,optional"`  // 邮箱
	Mobile       string `json:"mobile,optional"` // 手机号
	Gender       int32  `json:"gender,optional"` // 性别
	Avatar       string `json:"avatar,optional"` // 头像
	Introduction string `json:"introduction,optional"`
	Birthday     string `json:"birthday,optional"`
}

type RegisterResp struct {
	UserId       int64  `json:"userId"`       // 用户ID
	AccessToken  string `json:"accessToken"`  // JWT令牌
	RefreshToken string `json:"refreshToken"` // 刷新令牌
}

type Reply struct {
	Id              int64  `json:"id"`
	UserId          int64  `json:"userId"`
	UserName        string `json:"userName"`
	UserAvatar      string `json:"userAvatar"`
	Content         string `json:"content"`
	ReplyUserId     int64  `json:"replyUserId"`
	ReplyUserName   string `json:"replyUserName"`
	ReplyUserAvatar string `json:"replyUser"`
	CreatedAt       int64  `json:"createdAt"`
	Read            int    `json:"read"`
}

type SearchReq struct {
	PageRequest
	Type string `form:"type,default=all"`
}

type SearchResp struct {
	PageResponse
	Results []Article `json:"results"`
}

type SearchSuggestReq struct {
	Keyword string `json:"keyword"`
	Limit   int32  `json:"limit,default=10"`
}

type SearchSuggestResp struct {
	Keywords []string `json:"keywords"`
}

type StringValue struct {
	Value string `path:"value"`
}

type UpdateArticleCategoryReq struct {
	Id          int64  `json:"id""`                  // 分类ID
	Name        string `json:"name,optional"`        // 分类名称
	Description string `json:"description,optional"` // 分类描述
}

type UpdateArticleReq struct {
	Id         int64    `json:"id"`
	Title      string   `json:"title,optional"`
	Summary    string   `json:"summary,optional"`
	Content    string   `json:"content,optional"`
	Tags       []string `json:"tags,optional"`
	CategoryId int64    `json:"categoryId,optional"`
	Cover      string   `json:"cover,optional"`
}

type UpdateUserInfoReq struct {
	Nickname     string `json:"nickname,optional"`
	Avatar       string `json:"avatar,optional"`
	Introduction string `json:"introduction,optional"`
	Birthday     string `json:"birthday,optional"`
	Mobile       string `json:"mobile,optional"`
	Email        string `json:"email,optional"`
}

type UserInfo struct {
	Id           int64  `json:"id"`
	Username     string `json:"username"`
	Nickname     string `json:"nickname"`
	Avatar       string `json:"avatar"`
	Gender       int    `json:"gender"`
	Introduction string `json:"introduction"`
	Birthday     string `json:"birthday"`
	Mobile       string `json:"mobile"`
	Email        string `json:"email"`
}
