// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: sys.proto

package authservice

import (
	"context"

	"zero-admin/rpc/sys/sysclient"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddRolePermsRequest       = sysclient.AddRolePermsRequest
	AddScopeMenusRequest      = sysclient.AddScopeMenusRequest
	AssignUserRoleRequest     = sysclient.AssignUserRoleRequest
	BatchDeleteRolesRequest   = sysclient.BatchDeleteRolesRequest
	CreateMenuRequest         = sysclient.CreateMenuRequest
	CreateRoleRequest         = sysclient.CreateRoleRequest
	CreateScopeRequest        = sysclient.CreateScopeRequest
	CreateUserRequest         = sysclient.CreateUserRequest
	DeleteMenuRequest         = sysclient.DeleteMenuRequest
	DeleteRolePermsRequest    = sysclient.DeleteRolePermsRequest
	DeleteRoleRequest         = sysclient.DeleteRoleRequest
	DeleteScopeMenusRequest   = sysclient.DeleteScopeMenusRequest
	DeleteScopeRequest        = sysclient.DeleteScopeRequest
	DeleteUserRequest         = sysclient.DeleteUserRequest
	Empty                     = sysclient.Empty
	GetUserInfoRequest        = sysclient.GetUserInfoRequest
	Int64Value                = sysclient.Int64Value
	LoginRequest              = sysclient.LoginRequest
	LoginResponse             = sysclient.LoginResponse
	Menu                      = sysclient.Menu
	MenuListRequest           = sysclient.MenuListRequest
	MenuTreeResponse          = sysclient.MenuTreeResponse
	PageRequest               = sysclient.PageRequest
	PageResponse              = sysclient.PageResponse
	RefreshTokenRequest       = sysclient.RefreshTokenRequest
	RefreshTokenResponse      = sysclient.RefreshTokenResponse
	Role                      = sysclient.Role
	RoleInfo                  = sysclient.RoleInfo
	RoleListRequest           = sysclient.RoleListRequest
	RoleListResponse          = sysclient.RoleListResponse
	RoleScope                 = sysclient.RoleScope
	RoleScopeInfo             = sysclient.RoleScopeInfo
	Scope                     = sysclient.Scope
	ScopeInfo                 = sysclient.ScopeInfo
	ScopeListRequest          = sysclient.ScopeListRequest
	ScopeListResponse         = sysclient.ScopeListResponse
	ToggleRoleStatusRequest   = sysclient.ToggleRoleStatusRequest
	ToggleUserStatusRequest   = sysclient.ToggleUserStatusRequest
	UpdateMenuRequest         = sysclient.UpdateMenuRequest
	UpdateRolePermsRequest    = sysclient.UpdateRolePermsRequest
	UpdateRoleRequest         = sysclient.UpdateRoleRequest
	UpdateScopeRequest        = sysclient.UpdateScopeRequest
	UpdateUserPasswordRequest = sysclient.UpdateUserPasswordRequest
	UpdateUserRequest         = sysclient.UpdateUserRequest
	User                      = sysclient.User
	UserInfo                  = sysclient.UserInfo
	UserListRequest           = sysclient.UserListRequest
	UserListResponse          = sysclient.UserListResponse

	AuthService interface {
		// 用户登录
		Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
		// 刷新令牌
		RefreshToken(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*RefreshTokenResponse, error)
	}

	defaultAuthService struct {
		cli zrpc.Client
	}
)

func NewAuthService(cli zrpc.Client) AuthService {
	return &defaultAuthService{
		cli: cli,
	}
}

// 用户登录
func (m *defaultAuthService) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	client := sysclient.NewAuthServiceClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

// 刷新令牌
func (m *defaultAuthService) RefreshToken(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*RefreshTokenResponse, error) {
	client := sysclient.NewAuthServiceClient(m.cli.Conn())
	return client.RefreshToken(ctx, in, opts...)
}
