// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSysUser = "sys_user"

// SysUser 系统用户表
type SysUser struct {
	ID            int64      `gorm:"column:id;primaryKey;autoIncrement:true;comment:用户ID" json:"id"`                        // 用户ID
	Username      string     `gorm:"column:username;not null;comment:用户名" json:"username"`                                  // 用户名
	Password      string     `gorm:"column:password;not null;comment:密码（加密存储）" json:"password"`                             // 密码（加密存储）
	Salt          string     `gorm:"column:salt;not null;comment:盐值（用于密码加密）" json:"salt"`                                   // 盐值（用于密码加密）
	Email         string     `gorm:"column:email;not null;comment:邮箱" json:"email"`                                         // 邮箱
	Mobile        string     `gorm:"column:mobile;not null;comment:手机号" json:"mobile"`                                      // 手机号
	Avatar        string     `gorm:"column:avatar;not null;comment:头像URL" json:"avatar"`                                    // 头像URL
	RealName      string     `gorm:"column:real_name;not null;comment:真实姓名" json:"real_name"`                               // 真实姓名
	Gender        int32      `gorm:"column:gender;not null;comment:性别（0-未知，1-男，2-女）" json:"gender"`                         // 性别（0-未知，1-男，2-女）
	Status        int32      `gorm:"column:status;not null;default:1;comment:状态（0-禁用，1-正常）" json:"status"`                  // 状态（0-禁用，1-正常）
	LastLoginTime *time.Time `gorm:"column:last_login_time;comment:最后登录时间" json:"last_login_time"`                          // 最后登录时间
	LastLoginIP   string     `gorm:"column:last_login_ip;not null;comment:最后登录IP" json:"last_login_ip"`                     // 最后登录IP
	LoginCount    int32      `gorm:"column:login_count;not null;comment:登录次数" json:"login_count"`                           // 登录次数
	Creator       string     `gorm:"column:creator;not null;comment:创建人" json:"creator"`                                    // 创建人
	CreateTime    time.Time  `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"` // 创建时间
	Updater       string     `gorm:"column:updater;not null;comment:更新人" json:"updater"`                                    // 更新人
	UpdateTime    time.Time  `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_time"` // 更新时间
	DelFlag       int32      `gorm:"column:del_flag;not null;comment:删除标记（0-未删除，1-已删除）" json:"del_flag"`                    // 删除标记（0-未删除，1-已删除）
	Remark        string     `gorm:"column:remark;not null;comment:备注" json:"remark"`                                       // 备注
}

// TableName SysUser's table name
func (*SysUser) TableName() string {
	return TableNameSysUser
}
