// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSysOperateLog = "sys_operate_log"

// SysOperateLog 系统操作日志
type SysOperateLog struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:日志ID" json:"id"`                        // 日志ID
	UserID     int64     `gorm:"column:user_id;not null;comment:操作用户" json:"user_id"`                                   // 操作用户
	Operation  string    `gorm:"column:operation;not null;comment:操作描述" json:"operation"`                               // 操作描述
	Method     string    `gorm:"column:method;not null;comment:请求方法" json:"method"`                                     // 请求方法
	Params     *string   `gorm:"column:params;comment:请求参数" json:"params"`                                              // 请求参数
	IP         string    `gorm:"column:ip;not null;comment:IP地址" json:"ip"`                                             // IP地址
	CreateTime time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"` // 创建时间
}

// TableName SysOperateLog's table name
func (*SysOperateLog) TableName() string {
	return TableNameSysOperateLog
}
