// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSysRole = "sys_role"

// SysRole 系统角色表
type SysRole struct {
	ID          int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:角色ID" json:"id"`                        // 角色ID
	RoleName    string    `gorm:"column:role_name;not null;comment:角色名称" json:"role_name"`                               // 角色名称
	RoleCode    string    `gorm:"column:role_code;not null;comment:角色编码（如：ADMIN, USER）" json:"role_code"`                // 角色编码（如：ADMIN, USER）
	Description string    `gorm:"column:description;not null;comment:角色描述" json:"description"`                           // 角色描述
	Status      int32     `gorm:"column:status;not null;default:1;comment:状态（0-禁用，1-正常）" json:"status"`                  // 状态（0-禁用，1-正常）
	Creator     string    `gorm:"column:creator;not null;comment:创建人" json:"creator"`                                    // 创建人
	CreateTime  time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"` // 创建时间
	Updater     string    `gorm:"column:updater;not null;comment:更新人" json:"updater"`                                    // 更新人
	UpdateTime  time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_time"` // 更新时间
	DelFlag     int32     `gorm:"column:del_flag;not null;comment:删除标记（0-未删除，1-已删除）" json:"del_flag"`                    // 删除标记（0-未删除，1-已删除）
}

// TableName SysRole's table name
func (*SysRole) TableName() string {
	return TableNameSysRole
}
