// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSysLoginLog = "sys_login_log"

// SysLoginLog 登录日志表
type SysLoginLog struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:登录日志ID" json:"id"`                    // 登录日志ID
	Username  string    `gorm:"column:username;not null;comment:用户" json:"username"`                                 // 用户
	IP        string    `gorm:"column:ip;not null;comment:登录IP" json:"ip"`                                           // 登录IP
	Location  string    `gorm:"column:location;not null;comment:登录地址" json:"location"`                               // 登录地址
	Browser   string    `gorm:"column:browser;not null;comment:浏览器信息" json:"browser"`                                // 浏览器信息
	Os        string    `gorm:"column:os;not null;comment:操作系统信息" json:"os"`                                         // 操作系统信息
	Status    int32     `gorm:"column:status;not null;default:1;comment:登录状态（0-失败，1-成功）" json:"status"`              // 登录状态（0-失败，1-成功）
	Message   string    `gorm:"column:message;not null;comment:登录信息" json:"message"`                                 // 登录信息
	LoginTime time.Time `gorm:"column:login_time;not null;default:CURRENT_TIMESTAMP;comment:登录时间" json:"login_time"` // 登录时间
}

// TableName SysLoginLog's table name
func (*SysLoginLog) TableName() string {
	return TableNameSysLoginLog
}
