// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSysMenu = "sys_menu"

// SysMenu 系统菜单表
type SysMenu struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:菜单ID" json:"id"`                        // 菜单ID
	ScopeID    int64     `gorm:"column:scope_id;not null;comment:安全范围ID" json:"scope_id"`                               // 安全范围ID
	ParentID   int64     `gorm:"column:parent_id;not null;comment:父菜单ID (0表示根菜单)" json:"parent_id"`                     // 父菜单ID (0表示根菜单)
	MenuName   string    `gorm:"column:menu_name;not null;comment:菜单名称" json:"menu_name"`                               // 菜单名称
	MenuType   string    `gorm:"column:menu_type;not null;comment:菜单类型 (M-目录, C-菜单, F-按钮)" json:"menu_type"`            // 菜单类型 (M-目录, C-菜单, F-按钮)
	Path       string    `gorm:"column:path;not null;comment:路由路径" json:"path"`                                         // 路由路径
	Component  string    `gorm:"column:component;not null;comment:组件路径" json:"component"`                               // 组件路径
	Redirect   string    `gorm:"column:redirect;not null;comment:重定向路径" json:"redirect"`                                // 重定向路径
	Icon       string    `gorm:"column:icon;not null;comment:菜单图标" json:"icon"`                                         // 菜单图标
	Sort       int32     `gorm:"column:sort;not null;comment:排序" json:"sort"`                                           // 排序
	NoCache    int32     `gorm:"column:no_cache;not null;comment:是否缓存 (0-缓存, 1-不缓存)" json:"no_cache"`                   // 是否缓存 (0-缓存, 1-不缓存)
	Affix      int32     `gorm:"column:affix;not null;comment:是否固定在标签栏 (0-否, 1-是)" json:"affix"`                        // 是否固定在标签栏 (0-否, 1-是)
	External   int32     `gorm:"column:external;not null;comment:是否外部链接 (0-否, 1-是)" json:"external"`                    // 是否外部链接 (0-否, 1-是)
	Hidden     int32     `gorm:"column:hidden;not null;comment:是否隐藏 (0-显示, 1-隐藏)" json:"hidden"`                        // 是否隐藏 (0-显示, 1-隐藏)
	Status     int32     `gorm:"column:status;not null;default:1;comment:状态 (0-禁用, 1-正常)" json:"status"`                // 状态 (0-禁用, 1-正常)
	Creator    string    `gorm:"column:creator;not null;comment:创建人" json:"creator"`                                    // 创建人
	CreateTime time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"` // 创建时间
	Updater    string    `gorm:"column:updater;not null;comment:更新人" json:"updater"`                                    // 更新人
	UpdateTime time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_time"` // 更新时间
	DelFlag    int32     `gorm:"column:del_flag;not null;comment:删除标记 (0-未删除, 1-已删除)" json:"del_flag"`                  // 删除标记 (0-未删除, 1-已删除)
	Remark     string    `gorm:"column:remark;not null;comment:备注" json:"remark"`                                       // 备注
}

// TableName SysMenu's table name
func (*SysMenu) TableName() string {
	return TableNameSysMenu
}
