// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSysScope = "sys_scope"

// SysScope 系统安全范围表
type SysScope struct {
	ID          int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:范围ID" json:"id"`                        // 范围ID
	ScopeName   string    `gorm:"column:scope_name;not null;comment:范围名称" json:"scope_name"`                             // 范围名称
	ScopeCode   string    `gorm:"column:scope_code;not null;comment:范围编码" json:"scope_code"`                             // 范围编码
	Description string    `gorm:"column:description;not null;comment:范围描述" json:"description"`                           // 范围描述
	Sort        int32     `gorm:"column:sort;not null;comment:排序" json:"sort"`                                           // 排序
	Status      int32     `gorm:"column:status;not null;default:1;comment:0-禁用 1-启用" json:"status"`                      // 0-禁用 1-启用
	Creator     string    `gorm:"column:creator;not null;comment:创建人" json:"creator"`                                    // 创建人
	CreateTime  time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"` // 创建时间
	Updater     string    `gorm:"column:updater;not null;comment:更新人" json:"updater"`                                    // 更新人
	UpdateTime  time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_time"` // 更新时间
	DelFlag     int32     `gorm:"column:del_flag;not null;comment:删除标记（0-未删除，1-已删除）" json:"del_flag"`                    // 删除标记（0-未删除，1-已删除）
}

// TableName SysScope's table name
func (*SysScope) TableName() string {
	return TableNameSysScope
}
