// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: sys.proto

package server

import (
	"context"

	"zero-admin/rpc/sys/internal/logic/userservice"
	"zero-admin/rpc/sys/internal/svc"
	"zero-admin/rpc/sys/sysclient"
)

type UserServiceServer struct {
	svcCtx *svc.ServiceContext
	sysclient.UnimplementedUserServiceServer
}

func NewUserServiceServer(svcCtx *svc.ServiceContext) *UserServiceServer {
	return &UserServiceServer{
		svcCtx: svcCtx,
	}
}

// 用户管理
func (s *UserServiceServer) GetUserList(ctx context.Context, in *sysclient.UserListRequest) (*sysclient.UserListResponse, error) {
	l := userservicelogic.NewGetUserListLogic(ctx, s.svcCtx)
	return l.GetUserList(in)
}

func (s *UserServiceServer) GetUserById(ctx context.Context, in *sysclient.Int64Value) (*sysclient.UserInfo, error) {
	l := userservicelogic.NewGetUserByIdLogic(ctx, s.svcCtx)
	return l.GetUserById(in)
}

func (s *UserServiceServer) CreateUser(ctx context.Context, in *sysclient.CreateUserRequest) (*sysclient.UserInfo, error) {
	l := userservicelogic.NewCreateUserLogic(ctx, s.svcCtx)
	return l.CreateUser(in)
}

func (s *UserServiceServer) UpdateUser(ctx context.Context, in *sysclient.UpdateUserRequest) (*sysclient.UserInfo, error) {
	l := userservicelogic.NewUpdateUserLogic(ctx, s.svcCtx)
	return l.UpdateUser(in)
}

func (s *UserServiceServer) DeleteUser(ctx context.Context, in *sysclient.DeleteUserRequest) (*sysclient.Empty, error) {
	l := userservicelogic.NewDeleteUserLogic(ctx, s.svcCtx)
	return l.DeleteUser(in)
}

func (s *UserServiceServer) UpdateUserPassword(ctx context.Context, in *sysclient.UpdateUserPasswordRequest) (*sysclient.Empty, error) {
	l := userservicelogic.NewUpdateUserPasswordLogic(ctx, s.svcCtx)
	return l.UpdateUserPassword(in)
}

func (s *UserServiceServer) AssignUserRole(ctx context.Context, in *sysclient.AssignUserRoleRequest) (*sysclient.Empty, error) {
	l := userservicelogic.NewAssignUserRoleLogic(ctx, s.svcCtx)
	return l.AssignUserRole(in)
}

// 获取当前用户信息
func (s *UserServiceServer) GetUserInfo(ctx context.Context, in *sysclient.GetUserInfoRequest) (*sysclient.UserInfo, error) {
	l := userservicelogic.NewGetUserInfoLogic(ctx, s.svcCtx)
	return l.GetUserInfo(in)
}
