// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: sys.proto

package permissionservice

import (
	"context"

	"zero-admin/rpc/sys/sysclient"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateMenuRequest         = sysclient.CreateMenuRequest
	CreateRoleRequest         = sysclient.CreateRoleRequest
	CreateScopeRequest        = sysclient.CreateScopeRequest
	CreateUserRequest         = sysclient.CreateUserRequest
	DeleteMenuRequest         = sysclient.DeleteMenuRequest
	DeleteRoleRequest         = sysclient.DeleteRoleRequest
	DeleteScopeRequest        = sysclient.DeleteScopeRequest
	DeleteUserRequest         = sysclient.DeleteUserRequest
	Empty                     = sysclient.Empty
	GetCurrentUserRequest     = sysclient.GetCurrentUserRequest
	Int64Value                = sysclient.Int64Value
	LoginRequest              = sysclient.LoginRequest
	LoginResponse             = sysclient.LoginResponse
	Menu                      = sysclient.Menu
	MenuListRequest           = sysclient.MenuListRequest
	MenuTreeResponse          = sysclient.MenuTreeResponse
	PageRequest               = sysclient.PageRequest
	PageResponse              = sysclient.PageResponse
	RefreshTokenRequest       = sysclient.RefreshTokenRequest
	RefreshTokenResponse      = sysclient.RefreshTokenResponse
	Role                      = sysclient.Role
	RoleInfo                  = sysclient.RoleInfo
	RoleListRequest           = sysclient.RoleListRequest
	RoleListResponse          = sysclient.RoleListResponse
	Scope                     = sysclient.Scope
	ScopeInfo                 = sysclient.ScopeInfo
	ScopeListRequest          = sysclient.ScopeListRequest
	ScopeListResponse         = sysclient.ScopeListResponse
	UpdateMenuRequest         = sysclient.UpdateMenuRequest
	UpdateRoleRequest         = sysclient.UpdateRoleRequest
	UpdateScopeRequest        = sysclient.UpdateScopeRequest
	UpdateUserPasswordRequest = sysclient.UpdateUserPasswordRequest
	UpdateUserRequest         = sysclient.UpdateUserRequest
	User                      = sysclient.User
	UserInfo                  = sysclient.UserInfo
	UserListRequest           = sysclient.UserListRequest
	UserListResponse          = sysclient.UserListResponse

	PermissionService interface {
		// 用户管理
		GetUserList(ctx context.Context, in *UserListRequest, opts ...grpc.CallOption) (*UserListResponse, error)
		GetUserById(ctx context.Context, in *Int64Value, opts ...grpc.CallOption) (*UserInfo, error)
		CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*UserInfo, error)
		UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UserInfo, error)
		DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*Empty, error)
		UpdateUserPassword(ctx context.Context, in *UpdateUserPasswordRequest, opts ...grpc.CallOption) (*Empty, error)
		// 角色管理
		GetRoleList(ctx context.Context, in *RoleListRequest, opts ...grpc.CallOption) (*RoleListResponse, error)
		GetRoleById(ctx context.Context, in *Int64Value, opts ...grpc.CallOption) (*RoleInfo, error)
		CreateRole(ctx context.Context, in *CreateRoleRequest, opts ...grpc.CallOption) (*RoleInfo, error)
		UpdateRole(ctx context.Context, in *UpdateRoleRequest, opts ...grpc.CallOption) (*RoleInfo, error)
		DeleteRole(ctx context.Context, in *DeleteRoleRequest, opts ...grpc.CallOption) (*Empty, error)
		// 菜单管理
		GetMenuTree(ctx context.Context, in *MenuListRequest, opts ...grpc.CallOption) (*MenuTreeResponse, error)
		GetMenuById(ctx context.Context, in *Int64Value, opts ...grpc.CallOption) (*Menu, error)
		CreateMenu(ctx context.Context, in *CreateMenuRequest, opts ...grpc.CallOption) (*Menu, error)
		UpdateMenu(ctx context.Context, in *UpdateMenuRequest, opts ...grpc.CallOption) (*Menu, error)
		DeleteMenu(ctx context.Context, in *DeleteMenuRequest, opts ...grpc.CallOption) (*Empty, error)
		// 安全范围管理
		GetScopeList(ctx context.Context, in *ScopeListRequest, opts ...grpc.CallOption) (*ScopeListResponse, error)
		GetScopeById(ctx context.Context, in *Int64Value, opts ...grpc.CallOption) (*ScopeInfo, error)
		CreateScope(ctx context.Context, in *CreateScopeRequest, opts ...grpc.CallOption) (*ScopeInfo, error)
		UpdateScope(ctx context.Context, in *UpdateScopeRequest, opts ...grpc.CallOption) (*ScopeInfo, error)
		DeleteScope(ctx context.Context, in *DeleteScopeRequest, opts ...grpc.CallOption) (*Empty, error)
	}

	defaultPermissionService struct {
		cli zrpc.Client
	}
)

func NewPermissionService(cli zrpc.Client) PermissionService {
	return &defaultPermissionService{
		cli: cli,
	}
}

// 用户管理
func (m *defaultPermissionService) GetUserList(ctx context.Context, in *UserListRequest, opts ...grpc.CallOption) (*UserListResponse, error) {
	client := sysclient.NewPermissionServiceClient(m.cli.Conn())
	return client.GetUserList(ctx, in, opts...)
}

func (m *defaultPermissionService) GetUserById(ctx context.Context, in *Int64Value, opts ...grpc.CallOption) (*UserInfo, error) {
	client := sysclient.NewPermissionServiceClient(m.cli.Conn())
	return client.GetUserById(ctx, in, opts...)
}

func (m *defaultPermissionService) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*UserInfo, error) {
	client := sysclient.NewPermissionServiceClient(m.cli.Conn())
	return client.CreateUser(ctx, in, opts...)
}

func (m *defaultPermissionService) UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UserInfo, error) {
	client := sysclient.NewPermissionServiceClient(m.cli.Conn())
	return client.UpdateUser(ctx, in, opts...)
}

func (m *defaultPermissionService) DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := sysclient.NewPermissionServiceClient(m.cli.Conn())
	return client.DeleteUser(ctx, in, opts...)
}

func (m *defaultPermissionService) UpdateUserPassword(ctx context.Context, in *UpdateUserPasswordRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := sysclient.NewPermissionServiceClient(m.cli.Conn())
	return client.UpdateUserPassword(ctx, in, opts...)
}

// 角色管理
func (m *defaultPermissionService) GetRoleList(ctx context.Context, in *RoleListRequest, opts ...grpc.CallOption) (*RoleListResponse, error) {
	client := sysclient.NewPermissionServiceClient(m.cli.Conn())
	return client.GetRoleList(ctx, in, opts...)
}

func (m *defaultPermissionService) GetRoleById(ctx context.Context, in *Int64Value, opts ...grpc.CallOption) (*RoleInfo, error) {
	client := sysclient.NewPermissionServiceClient(m.cli.Conn())
	return client.GetRoleById(ctx, in, opts...)
}

func (m *defaultPermissionService) CreateRole(ctx context.Context, in *CreateRoleRequest, opts ...grpc.CallOption) (*RoleInfo, error) {
	client := sysclient.NewPermissionServiceClient(m.cli.Conn())
	return client.CreateRole(ctx, in, opts...)
}

func (m *defaultPermissionService) UpdateRole(ctx context.Context, in *UpdateRoleRequest, opts ...grpc.CallOption) (*RoleInfo, error) {
	client := sysclient.NewPermissionServiceClient(m.cli.Conn())
	return client.UpdateRole(ctx, in, opts...)
}

func (m *defaultPermissionService) DeleteRole(ctx context.Context, in *DeleteRoleRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := sysclient.NewPermissionServiceClient(m.cli.Conn())
	return client.DeleteRole(ctx, in, opts...)
}

// 菜单管理
func (m *defaultPermissionService) GetMenuTree(ctx context.Context, in *MenuListRequest, opts ...grpc.CallOption) (*MenuTreeResponse, error) {
	client := sysclient.NewPermissionServiceClient(m.cli.Conn())
	return client.GetMenuTree(ctx, in, opts...)
}

func (m *defaultPermissionService) GetMenuById(ctx context.Context, in *Int64Value, opts ...grpc.CallOption) (*Menu, error) {
	client := sysclient.NewPermissionServiceClient(m.cli.Conn())
	return client.GetMenuById(ctx, in, opts...)
}

func (m *defaultPermissionService) CreateMenu(ctx context.Context, in *CreateMenuRequest, opts ...grpc.CallOption) (*Menu, error) {
	client := sysclient.NewPermissionServiceClient(m.cli.Conn())
	return client.CreateMenu(ctx, in, opts...)
}

func (m *defaultPermissionService) UpdateMenu(ctx context.Context, in *UpdateMenuRequest, opts ...grpc.CallOption) (*Menu, error) {
	client := sysclient.NewPermissionServiceClient(m.cli.Conn())
	return client.UpdateMenu(ctx, in, opts...)
}

func (m *defaultPermissionService) DeleteMenu(ctx context.Context, in *DeleteMenuRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := sysclient.NewPermissionServiceClient(m.cli.Conn())
	return client.DeleteMenu(ctx, in, opts...)
}

// 安全范围管理
func (m *defaultPermissionService) GetScopeList(ctx context.Context, in *ScopeListRequest, opts ...grpc.CallOption) (*ScopeListResponse, error) {
	client := sysclient.NewPermissionServiceClient(m.cli.Conn())
	return client.GetScopeList(ctx, in, opts...)
}

func (m *defaultPermissionService) GetScopeById(ctx context.Context, in *Int64Value, opts ...grpc.CallOption) (*ScopeInfo, error) {
	client := sysclient.NewPermissionServiceClient(m.cli.Conn())
	return client.GetScopeById(ctx, in, opts...)
}

func (m *defaultPermissionService) CreateScope(ctx context.Context, in *CreateScopeRequest, opts ...grpc.CallOption) (*ScopeInfo, error) {
	client := sysclient.NewPermissionServiceClient(m.cli.Conn())
	return client.CreateScope(ctx, in, opts...)
}

func (m *defaultPermissionService) UpdateScope(ctx context.Context, in *UpdateScopeRequest, opts ...grpc.CallOption) (*ScopeInfo, error) {
	client := sysclient.NewPermissionServiceClient(m.cli.Conn())
	return client.UpdateScope(ctx, in, opts...)
}

func (m *defaultPermissionService) DeleteScope(ctx context.Context, in *DeleteScopeRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := sysclient.NewPermissionServiceClient(m.cli.Conn())
	return client.DeleteScope(ctx, in, opts...)
}
