package common

type PermType = int32

const (
	// 为了方便管理，用户2 4 8权限的都自动加上1权限
	// 0-无权限，1-读，2-写，4-创建，8-删除
	PERM_NONE PermType = 0

	PERM_READ = 1 << (iota - 1)
	PERM_WRITE
	PERM_CREATE
	PERM_DELETE
	PERM_READ_WRITE               PermType = PERM_READ | PERM_WRITE
	PERM_READ_CREATE              PermType = PERM_READ | PERM_CREATE
	PERM_READ_DELETE              PermType = PERM_READ | PERM_DELETE
	PERM_WRITE_CREATE             PermType = PERM_WRITE | PERM_CREATE
	PERM_WRITE_DELETE             PermType = PERM_WRITE | PERM_DELETE
	PERM_CREATE_DELETE            PermType = PERM_CREATE | PERM_DELETE
	PERM_READ_WRITE_CREATE        PermType = PERM_READ | PERM_WRITE | PERM_CREATE
	PERM_READ_WRITE_DELETE        PermType = PERM_READ | PERM_WRITE | PERM_DELETE
	PERM_READ_CREATE_DELETE       PermType = PERM_READ | PERM_CREATE | PERM_DELETE
	PERM_WRITE_CREATE_DELETE      PermType = PERM_WRITE | PERM_CREATE | PERM_DELETE
	PERM_READ_WRITE_CREATE_DELETE PermType = PERM_READ | PERM_WRITE | PERM_CREATE | PERM_DELETE
	PERM_ALL                      PermType = PERM_READ_WRITE_CREATE_DELETE
)
